- src/core.ts
- test/makereactive.js
This code:
```js
var arr = mobservable.observable([]);
var person = Object.freeze({ name: 'bob' })
arr.push(person)
```
throws error `Cannot define property:$mobservable, object is not extensible.`
This also prevents from pushing react elements into mobservable array:
```
buttons.push(<button title="test" />);
```
> Support frozen objects

- README.md
https://mobxjs.github.io/ 404s and does not actually link to the API documentation, so here's a fix!
> Fix 404 in link to API documentation from readme

- docs/refguide/extending.md
Previous text was a run-on sentence and was redundant.
> Edited for readability

- docs/refguide/computed-decorator.md
computed was not imported in first example.
> Add missing import

- docs/SUMMARY.md
- docs/best/actions.md
- docs/best/react-performance.md
- docs/best/store.md
- docs/best/syntax.md
- docs/faq/faq.md
- docs/intro/concepts.md
- docs/intro/overview.md
- docs/refguide/api.md
- docs/refguide/autorun-async.md
- docs/refguide/computed-decorator.md
- docs/refguide/create-transformer.md
- docs/refguide/expr.md
- docs/refguide/extending.md
- docs/refguide/extras.md
- docs/refguide/is-observable.md
- docs/refguide/map.md
- docs/refguide/modifiers.md
- docs/refguide/observable-decorator.md
- docs/refguide/observable.md
- docs/refguide/observe.md
- docs/refguide/observer-component.md
- docs/refguide/transaction.md
- docs/refguide/when.md
Another round of nitpicking changes... :smile: 
Beyond fixing typos and improving consistency (case of names, among others), I made an editorial change I mentioned in issues: I removed the two mentions of fastArray, one in text and one in code.
For the latter, I replaced with `m.asFlat([])` (I hope it is correct), for the former, I mentioned this "trick".
Obviously, feel free to revert or change any modification I made...
> Fix typos and improve consistency

- docs/intro/concepts.md
changed to correct spelling for automatically.
> corrected spelling for automatically

- package.json
- src/types/observablearray.ts
makeNonEnumerable ObservableArray.prototype have weird result in iOS 7.x.
**toString** changed to **toLocalString**, **toLocalString** changed to **remove**, but **remove** changed **toString** !!!
> fix makeNonEnumerable bug in iOS 7.x 

- docs/book.json
I noticed the docs were using the old name
> Fixed Disqus short name

- getting-started.html
Spelling issues / omitted words / grammar issues can be a turn off for some people in an official project tutorial, where people might think that they reflect the quality of the library. I went ahead and fixed these issues.
> Fixed a few language errors in getting-started.html

- README.md
"An" should be "a" in line 144 of the readme:
"...changing some data might influence a seemingly unrelated component in ~~an~~ **a** corner case.  Mobx won't forget."
> Fixed a typo in readme.

- src/core/computedvalue.ts
- test/observe.js
The problem:
```js
var obs = observable({a: 1, b: 1});
var targetValue = observable(1);
var someComputed = computed(() => targetValue.get());
someComputed.observe(() => console.log(obs.a, obs.b));
targetValue.set(2); // ok, logs 1 1
obs.a = 2;          // fail, logs 2 1
obs.b = 2;          // fail, logs 2 2
```
> 'computed.observe should not establish new observers on callback'

- getting-started.html
When double clicked, the prompt showed, if i canceled it, the value was cleared. I thought this might be a bug, I would expect the value to be kept.
> Fixed bug.

- refguide/transaction.html
"transactoin" -> "transaction" in title
> gh-pages: fix typo

- src/core/action.ts
After applying `@action` decorator `this` is equal to the first class instance of method, that this decorator was applied to.
For example:
```js
class Component {
constructor(componentNum) {
this.name = `component-${componentNum}`;
}
@action execAction = () => {
console.log(this.componentNumber);
}
}
const c1 = new Component(1);
const c2 = new Component(2);
c1.execAction(); // logs: "component-1"
c2.execAction(); // logs: "component-1" instead of "component-2"
```
This used to happen because of memoization in `babelActionValueDecorator`. This PR removes that memoization.
> Fix context in @action

- src/core/derivation.ts
"... calculating **the** your computed value ..." -> "... calculating your computed value ..."
> Fix typo in error message.

- docs/refguide/observe.md
The doc says `observer` when it means `observe`.
> Fix typo in docs: observer -> observe.

- src/api/computeddecorator.ts
- src/api/extendobservable.ts
- src/api/observabledecorator.ts
- src/core/action.ts
- src/types/observableobject.ts
- src/types/type-utils.ts
- src/utils/decorators.ts
- test/babel/babel-tests.js
- test/typescript-tests.ts
* decorators are now stored on prototype if possible: gives significant perfomance improvements in CPU and MEM usage (30-50% in benchmarks)
* subtle differences between typescript and babel are now largely gone
* Object.keys(instance) will no longer report observable properties, in contrast to for .. in ...
* more code reuse between decorators
* improved test coverage
* This PR also fixes #288 and makes it a lot easier to make decorators configurable (see also #211)
Benchmark of creating and modifying 100K objects:
language | instantiating (ms) | modifying(ms) | peak mem
---- | --- | ---- | ---
ts (before PR) |  1308 |  7491 | 360MB
ts | 938 | 2222 | 198MB
babel (before PR) | 14 | 5348 | 374MB
babel | 19 | 2046 | 194MB
> Fix decorators

- getting-started.html
Makes it consistent with the title tag, which says ten. 
Not normally an issue except when shared on social networks. e.g. facebook messenger:
Is it five? Or ten? 😀
> Fix inconsistent title/desc in getting-started doc

- src/types/observablearray.ts
[MDN Array find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) entry states:
> The find() method returns a value in the array, if an element in the array satisfies the provided testing function. Otherwise undefined is returned.
> Fixed #341 ObservableArray.find return null instead of undefined

- src/utils/decorators.ts
When tsc target is set to ES3 (default), it won't add 3'rd argument for decorator https://github.com/Microsoft/TypeScript/blob/v1.8.10/src/compiler/emitter.ts#L5707
Then it won't use Object.defineProperty https://github.com/Microsoft/TypeScript/blob/v1.8.10/src/compiler/emitter.ts#L364
I don't know, whether we should care about this setup, because mobx itself is not usable under ES3 environment, but this fixes problem on updating from mobx 2.2.2
> Fix decorator in typescript targeting ES3

- src/api/observabledecorator.ts
Since v2.3.1 `@observable` Typescript decorator does't define instance property, so, for example:
```
class Store {
@observable cats = 5;
}
var store = new Store();
store.hasOwnProperty('cats'); // returns false
Object.assign({}, store); // returns {}
```
Note, that it didn't define instance property before v2.3.1 in Babel version, only in Typescript one.
@mweststrate, if this is expected behaviour, please close my pr.
> Make observable decorator define instance properties

- docs/refguide/when.md
... since it throws "@observable can not be used on getters, use @computed instead".
> Documentation: @observable should be @computed in "when" example

- src/types/observablearray.ts
- test/action.js
- test/array.js
- test/cycles.js
- test/extras.js
- test/spy.js
More info: #364
All the tests are now passing in Safari, Chrome, Firefox.
Chrome & FF assign variable name to function name when assigned to variable, so some test were failing.
```js
var myAnonymous = () => {};
myAnonymous.name // 'myAnonymous'
```
fixed buffer autoincrease bug:
```js
var i = observable(new Array(1000))
i.observe(a => console.log(a))
i[999] = "v" // Ok, triggers reaction
i[1000] = "v" // Fail, nothing happen
i[1001] = "v" // Fail, nothing happen
i[1002] = "v" // Fail, nothing happen
i.length // Fail, 1000
```
> Fix ObservableArray setters in Safari and buffer autoincreace

- src/utils/decorators.ts
If descriptor was falsy (line 33), a newDescriptor was created (line 35) but it was not actually used in line 55.
This broke Angular 2 zone.js for me with TypeError: desc is undefined and the proposed change fixes that.
> use created descriptor for defineProperty

- src/api/autorun.ts
- src/core/reaction.ts
- src/mobx.ts
- test/autorun.js
- test/autorunAsync.js
- test/reaction.js
@mweststrate, proposed this in https://github.com/mobxjs/mobx/pull/367/files#diff-b7cd2bd0ae3078ef83015cbfa3499bf6
Reaction instance is being passed to
- mobx.reaction's expression and effect functions
- mobx.autorun's view
- mobx.autorunAsync's view
So you can do:
```js
autorun(r => {
if (condition) r.dispose();
});
reaction(
r => {
if (condition) r.dispose();
return something.get(); 
},
v => {}
)
reaction(
() => something.get(),
(v, r) => {
if (condition) r.dispose();
}
)
```
Will add this to docs in another PR.
> Pass Reaction as an argument

- src/api/computeddecorator.ts
When using `@computed` on a property, `originalDescriptor` is undefined thus the access to `get` failed before the invariant was reached.
I just (stupidly) wrote a `@computed` decorator in front of a property like this:
@computed urls: string[] = [];
The error message I saw in browser console was
mobx.js:180 Uncaught TypeError: Cannot read property 'get' of undefined
With this change a nice error message will be shown instead.
> Improve error msg when wrongly using `@computed`

- src/core/reaction.ts
- test/reaction.js
Hi,
Updated the exception message for cyclic reactions. It is a matter of taste, so just wanted to check your opinion. I hope it helps.
Cheers
> Refactor max iterations exception message

- src/utils/utils.ts
`isPlainObject(Object.create(null))` should return true
> Concider object with null prototype a plain object

- src/api/action.ts
Trying to use action as a function wrapper on promises, like this:
```ts
import {action} from "mobx"
fetch().then(action(result => {
}))
```
Produces "Parameter 'result' implicitly has an 'any' type", if compiled with `noImplicitAny` option.
This PR adds some overloads for `action` declaration, which fixes this issue.
> Typescript: Add granular overloads for `action`, which fixes "Parameter XXX implicitly has an 'any' type"

- src/api/action.ts
The return type of `runInAction` actually is return type of wrapped function.
> Typescript: Add proper return type of `runInAction` function.

- src/types/observablearray.ts
- src/types/observablemap.ts
Typescript has a cool feature called `user type guard functions`, which helps to
narrow type of variable. This PR makes `isObservableArray` and `isObservableMap`
user type guard functions.
> Make `isObservableArray` and `isObservableMap` type guards.

- best/react-performance.html
- docs/best/react-performance.md
- docs/refguide/api.md
- docs/refguide/observe.md
- docs/refguide/observer-component.md
- refguide/api.html
- refguide/observe.html
- refguide/observer-component.html
fix `be used be used` -> `be used`
> fix typo on api's page

- docs/refguide/api.md
Due to a missing char, the `@inject` doc at line 135 was not rendering properly in markdown. I let it be a few times and figured someone else might create a PR for it but I might as well do it. :)
Cheers!
> Fix broken markdown for @inject documentation.

- docs/refguide/autorun-async.md
Added a tiny bit of documentation for autorunAsync.
BTW, is there a guideline regarding documentation improvements besides the short contribution note in the Readme file?
E.g. `scope` works same on many methods and does not need repeated explanation everywhere, however it is not mentioned anywhere in the docs yet.
Should the different method signatures be added at the top of each page? Or should the alternatives be mentioned below (as in this PR) or not at all?
> add debug and scope info

- src/api/observable.ts
- src/mobx.ts
- src/types/observableobject.ts
- test/typescript-tests.ts
> feature(api): tell consumers when their objects are observable

- src/api/extendobservable.ts
- src/api/iscomputed.ts
- src/api/isobservable.ts
- src/api/observable.ts
- src/api/tojs.ts
- src/api/whyrun.ts
- src/core/action.ts
- src/core/atom.ts
- src/core/computedvalue.ts
- src/core/derivation.ts
- src/core/reaction.ts
- src/core/spy.ts
- src/types/modifiers.ts
- src/types/observablearray.ts
- src/types/observablemap.ts
- src/types/observableobject.ts
- src/types/observablevalue.ts
- src/types/type-utils.ts
- src/utils/utils.ts
eliminate `instanceof` checks by introducing on the prototype to identify the type. Note that different property names are used so that inheritance based checks work (actually only applicable for `ObservableValue` I think, so could be skipped)
@amir-arad / @andykog up for a review?
> Fix 571 no instanceof

- README.md
If you are creating an extensive issue, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted ;-).
PR checklist:
now your OpenCollective backers&sponsors will appear directly on the readme. 
See how it will look: https://github.com/apex/apex#backers 
deets: https://github.com/opencollective/opencollective/wiki/Github-banner
Added some badges @ the top as well. :)
> added backers & sponsors

- src/types/modifiers.ts
Currently in cases like this
```
reaction(asStructure(() => ({a: 1, b: '1'})), d => ...)
```
type of `d` is `any` while it can be inferred. Another type definition for `asStructure` is added to cover this particular case (which is quite often, at least for me).
Didn't add test because don't know how to test it. Declaration covers very small set of use cases. When it doesn't work, `d` type is `any` which can't be tested against. Playing in VSCode shown positive results.
Certainly it can cause a lot of compilation errors in existing code because of type mismatch (which is good i guess).
> Added asStructure definition accepting function to use with reaction.

- docs/refguide/action.md
This PR adds a note about our new [babel-plugin-mobx-deep-action](https://github.com/mobxjs/babel-plugin-mobx-deep-action).
> Add note about babel-plugin-mobx-deep-action

- src/types/observablearray.ts
- test/array.js
Adds a .move method for moving individual elements around in an observable array. This is convenient to do that in an atomic way since otherwise a move can only be expressed by at least two splices. The resulting change is still one splice, but one that replace all array members: it's up to client to recognize this fact.
For documentation, add the following to https://mobxjs.github.io/mobx/refguide/array.html :
`move(fromIndex, toIndex)` Moves the element at index `fromIndex` to index `toIndex` in the array, with other array members shifting at most 1 position, and either all right or all left depending on the value of `toIndex - fromIndex`.
Examples: `observable([0, 1, 2, 3]).move(1, 2).slice()` yields `[0, 2, 1, 3]`, and `observable([0, 1, 2, 3]).move(3, 1).slice()` yields `[0, 3, 1, …
> add ObservableArray.move method

- docs/faq/examples.md
Hi I created React + mobx example project.
So I want to add my project to examples list.
Thank you.
> Add react mobx examples

- CHANGELOG.md
- src/api/autorun.ts
- src/api/createtransformer.ts
- src/core/computedvalue.ts
- src/core/derivation.ts
- src/core/globalstate.ts
- src/core/observable.ts
- src/core/reaction.ts
- src/mobx.ts
- test/action.js
- test/api.js
- test/errorhandling.js
- test/extras.js
- test/makereactive.js
- test/observables.js
- test/reaction.js
- test/spy.js
- test/utils/test-utils.js
Fixes #731 
* computed values that throw, store the exception and throw it to the next consumer(s). They keep tracking their data, so they are able to recover
* reactions will always catch their exceptions, and just log the error. They will keep tracking their data, so they are able to recover
* the disposer of a reaction exposes an `onError(handler)`  function to be able to attach custom error handling logic to an reaction (this intercepts the default behavior)
* `extras.onReactionError` can be used to register a global onError handler for reactions (will fire after spy `"error"` event
> 731 improve errorhandling

- docs/best/pitfalls.md
- docs/intro/overview.md
- docs/refguide/action.md
- docs/refguide/api.md
- docs/refguide/array.md
- docs/refguide/boxed.md
- docs/refguide/computed-decorator.md
- docs/refguide/extend-observable.md
- docs/refguide/map.md
- docs/refguide/modifiers.md
- docs/refguide/object.md
- docs/refguide/reaction.md
- docs/refguide/when.md
> Update docs to mobx 3

- CHANGELOG.md
Minor changelog update to show upgrade path for @computed({asStructure: true})
> Include computed.struct in mobx3 changelog

- flow-typed/mobx.js
Fixes the flowtype definition for toJS. The original source code allows `detectCycles` and `___alreadySeen` to be null.
PR checklist:
> Fix toJS flowtype definition

- flow-typed/mobx.js
Fixes runInAction flow type, name is not mandatory
> Fixes runInAction flow type, name is not mandatory

- src/utils/utils.ts
- test/observables.js
In an environment where the ES6 Map is missing, any call to observable() will throw an uncaught error at the `isES6Map` check in `utils/utils.ts` and the observable won't be created. This pull request is a simple fix that makes sure that we don't try to call `type instanceof undefined`.
PR checklist:
> Missing es6 map error

- README.md
- package.json
- scripts/single-file-build.js
Also publish the flow typings to npm, so we can use them. 
Where should I add the documentation on how to use this? You should add this to the `[libs]` section of your .flowconfig. 
```
[libs]
node_modules/mobx/lib/mobx.js.flow
```
> Also publish flow typings to npm

- src/types/observablevalue.ts
- test/observables.js
As per #561.
Big thanks to @wildeyes for helping me!
Note: `console.log(mobx.observable(3))` returns `ObservableValue` and not `3`. Is this okay?
#GoodnessSquad
> Add support for Symbol.toPrimitive() and valueOf() on observables #GoodnessSquad

- CHANGELOG.md
- src/core/computedvalue.ts
- src/types/observablevalue.ts
- src/utils/utils.ts
- test/makereactive.js
- test/observables.js
> Add support for `toPrimitive` and `valueOf` on computed and observable values

- docs/faq/faq.md
`rx-mobx` is deprecated in favour of `mobx-utils`.
> Link to mobx-utils instead of rx-mobx in FAQ

- src/api/action.ts
- src/core/action.ts
- src/mobx.ts
As discussed with @mweststrate, added IAction to the return type of an action() call.
PR checklist:
> feat: added IAction to action function return type

- flow-typed/mobx.js
This PR adds two new type definitions for the `action()` method:
`action(name: string, func: T): T`
`action(func: T): T`
More specifically, this types the non-decorator implementation of `action()`.
The existing `action()` type definition returns `any`, which causes type information associated with the wrapped function to be lost. At some point, we should probably investigate flow-type support for decorators. I could be mistaken but I think decorators in flow-type either causes warnings or are ignored, so the current definition may not provide the intended value.
> Improve flow typing for action method

- docs/README.md
Generally, "but also" is preceded by "not only", which makes this sentence clearer (it's a correlative conjunction). The previous text said that the values _can't_ be primitive values, but of course they can. It is that they are not _limited_ to being primitive values.
> Clarify English

- docs/refguide/computed-decorator.md
- docs/refguide/observable-decorator.md
Some sneaky numbers managed to find their way in from typed land.
> Remove types in Javascript code examples

- best/pitfalls.html
- best/pitfalls.md
- best/react-performance.html
- docs/best/pitfalls.md
- docs/best/react-performance.md
The use of `lately` is confusing (and I think, incorrect) in this context. "lately" means "recently" -- "not long ago". What the docs mean is to dereference _late_ in the process.
> [docs] lately → late

- docs/best/pitfalls.md
`@observable` <strong>'</strong>s is possessive. We want the plural, `@observable`s.
PR checklist:
> Removed unnecessary apostrophe from pitfalls.md

- PULL_REQUEST_TEMPLATE.md
TIL GitHub will still use the old PR template if you send a PR to update the PR template... 😄 
PR checklist:
The above process doesnt apply to doc updates etc.
> Added missing apostrophe to PR template

- docs/refguide/untracked.md
The original typo made it seem like the two approaches can happen sequentially when, after re-reading, it seems like the intent is to convey that `untracked` is a lower-level operation than `(@)action`, and that if you're using `(@)action`, then `untracked` isn't necessary.
> Fix typo, clarify comparison

- test/array.js
`typeof` operator also returns `"object"` for native array
It does not return `"array"` for anything
This test case is unnecessary
> Remove test case of typeof operator on observable array

- docs/intro/concepts.md
Corrected a few minor spelling and grammar issues in the [Concepts & Principles](https://mobx.js.org/intro/concepts.html) GitHub page.
> Minor spelling and grammar corrections

- CHANGELOG.md
Seems like the version history has been off by 1 since `3.1.1` was introduced but left unpublished. Latest version of mobx published to npm is 3.1.3
> Fix CHANGELOG.md version history

- CHANGELOG.md
- src/types/modifiers.ts
- test/map.js
> fix/deepEnhancer: create map instead of shallow map

- docs/refguide/computed-decorator.md
> Fix "catched" typo in docs

- src/types/observablemap.ts
This PR addresses #847 and splits `IMapChange` into `IMapChangeUpdate`, `IMapChangeAdd` and `IMapChangeDelete`.
The type of `IMapWillChange` is also updated so that its `newValue` field is of type `T` (and because the field is optional its type is implicitly `T|undefined`).
> Stricter typing of IMapChange and IMapWillChange

- docs/best/react.md
Fix code example:
```javascript
@observer class MyComponent extends React.component {
author;
constructor(props) {
super(props)
this.author = props.message.author;
}
render() {
return <div>{author.name}</div> // ---->   should be this.author.name
}
}
```
> Fix missing `this` in code example

- src/types/intercept-utils.ts
My TS compiler complains on this:
```
ERROR in ./src/types/intercept-utils.ts
(30,29): error TS2345: Argument of type 'T | null' is not assignable to
parameter of type 'T'.
Type 'null' is not assignable to type 'T'.
webpack: Failed to compile.
```
> Fixed typescript error

- src/api/createtransformer.ts
- test/transform.js
> Support primitives as memoization key for `createTransformer`

- docs/refguide/api.md
Updated spelling of `compuations` to `computations` in api documentation.
> Updated spelling of compuations to computations

- flow-typed/mobx.js
- src/api/autorun.ts
I stumbled on this:
```javascript
autorunAsync(async () => {}, 500)
```
being labeled as wrong by flow, because async function always returns a promise.
```
src/routes/areas-to-follow.js:23
23:     this.disposer = autorunAsync(async () => {
^ Promise. This type is incompatible with the expected param type of
312:   declare function autorunAsync(func: (r: IReactionPublic) => void, delay?: number, scope?: any): any
^^^^ undefined. See lib: node_modules/mobx/lib/mobx.js.flow:312
```
> change the return type of a function parameter of autorun/autorunAsync to any

- flow-typed/mobx.js
- src/types/observablearray.ts
- test/array.js
refs #934 
Implement `ObservableArray#findIndex` to accepts 3rd arguments like `ObservableArray#find`.
I'll send another PR for updating docs later. -> #938
> ObservableArray#findIndex

- flow-typed/mobx.js
Flowtype definition was missing only for `observable.map#replace`.
> Add flow type of ObservableMap.replace

- .gitignore
- package.json
- scripts/build.js
- src/api/observable.ts
- src/types/observablearray.ts
- tsconfig.json
This output file (mobx.module.js) is built with the ES2015 typescript target, so no ES2015 features get transpiled, and es module exports are preserved. This allows consumers of mobx to take advantage of
tree-shaking bundlers such as rollupjs and webpack 2.
I was considering using the `.mjs` extension, as that looks like it will be the most likely extension for es modules, but as it's not supported in node at all at the moment, I decided against it. 
Should es2015+ features still be transpiled?
I'm not sure what the standard practice here is. Webpack usage typically avoids processing code from `node_modules`, so a consumer trying to include the `mobx` module version would have to be made aware that they need to include mobx in their transpilation process if they're targeting ES5. However, …
> add an es-modules build (referenced with pkg.module)

- flow-typed/mobx.js
Consistently use commas, add variants of observe, add IValueDidChange interface.
> Update flow types

- src/mobx.ts
In Webpack 2, `exports` isn't passed in to the module's function scope, rather `module` is. I've modified the code here to be a bit more forgiving depending on the environment that the module is included in, but not sure what to do when neither `module` _or_ `exports` is available.
My first instinct in that scenario would be to just essentially no-op, as the rest of the module's exports are still intact (and this is essentially a hack anyways)
Fixes #1039
> workaround for webpack build not finding `exports`

- src/mobx.ts
Seems that using `exports` / `module.exports` has become tuff nowadays (https://github.com/mobxjs/mobx-react/pull/265, https://github.com/mobxjs/mobx/issues/1039)
> Drop using module.exports for devtools

- README.md
Continuing work from #1053 , I've added a link on the README to the awesome list.
Is this what you were thinking, @mweststrate , or would you like it more prominent?
> Add link to awesome mobx to readme

- docs/refguide/observable.md
Update documentation: invite users to use `observable.map` instead of the old `asMap` modifier.
Let me know if there is other sections referring to legacy modifiers that you would like to see updated!
> [DOCS] Update references `asMap` to `observable.map`

- docs/best/decorators.md
By default typescript uses `es3` target. So it will be good to have note about minimum ts target.
close #1073 #1074
> Note about minimum ts target for decorators

- CHANGELOG.md
- flow-typed/mobx.js
- src/types/observablearray.ts
- test/typescript/typescript-tests.ts
The `intercept` method of `ObservableArray` was using the types
`IArrayChange` and `IArraySplice`, but should have used the types
`IArrayWillChange` and `IArrayWillSplice` instead, as there are less
properties available when intercepting a change than when observing one.
> Improve typings of intercept method of observable array

- flow-typed/mobx.js
Flow reports uncovered code when "useStrict(true)" is used due to the defined return type. Because then useStrict function doesn't return a value, a void return definition is most appropriate.
PR checklist:
> useStrict doesn't return a value

- src/utils/utils.ts
webpack UMD builds pass in the global object (`global` in node and `window` in the browser) as a parameter named `global`. In RollupJS this is not the case. Access to the global object has to be handled manually, so let's just check for `window`, and if it doesn't exist fall back to `global`.
> fix access to global object (fixes #1109)

- src/api/intercept.ts
Use an index type for the property name argument when using intercept for better type checking.
> Use Index Type for property name in intercept

- docs/refguide/observer-component.md
According to issue #1113 (https://github.com/mobxjs/mobx/issues/1113) create an explanation like this: "The reactive state will be picked up by render but will not explicitly invoke other React lifecycle methods except componentWillUpdate and component did update. If you need other React lifecycle methods, just use the normal React state based APIs."
> Clarify docs about React lifecycles hooks #GoodnessSquadKyiv

- package.json
- scripts/build.js
I've just been playing around with the [@std/esm](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b) loader, which makes reference to the fact that Node's ES6 module support is going to be tied to the file extension `*.mjs`. I admit I don't know much context around this issue but I saw this and thought it might make sense to follow the new convention.
> Rename ESM output to .mjs

- src/types/observableobject.ts
- test/observables.js
> #1121 add possibility to redefine a computed property #GoodnessSquadKyiv

- CHANGELOG.md
- package.json
- scripts/build.js
Reverts mobxjs/mobx#1131
Reverted `.mjs` extension until https://github.com/facebook/metro-bundler/issues/59 is resolved
> Revert "Rename ESM output to .mjs"

- src/types/observablearray.ts
[Weex](https://github.com/alibaba/weex) is a framework like `ReactNative`. It runs javascript in JavaScriptCore/V8 runtime and freezed `Array.prototype`.
Mobx is a awesome library so I want make it works in weex. `ObservableArray` in mobx override `push/sort/etc` could not run in weex. We'd better make this original array method writeable in `StubArray.prorotype`.
See https://github.com/alibaba/weex/pull/1529
> Support weex

- src/api/iscomputed.ts
- test/observables.js
Fix for #1120: isComputed now returns false for non existing properties.
PR checklist:
> Fix #1120: isComputed should return false for non existing property

- docs/refguide/api.md
- docs/refguide/computed-decorator.md
1. Updated description of `observable` rules for type of received argument which contradicted the [source code](https://github.com/mobxjs/mobx/blob/a867e87788a3aeb5d03a0a99f8379c13edd6be25/src/utils/utils.ts#L78)
2. Few typos/missing words
> Updating docs (api.md, computed-decorator.md)

- docs/refguide/observable-decorator.md
The example also uses `computed` but didn't import the symbol
> observable-decorator.md doc fix

- src/api/extendobservable.ts
In Typescript 2.6, Object.getOwnPropertyDescriptor now returns `PropertyDescriptor | undefined`. Assert that the type is still just `PropertyDescriptor`, because it is checked with `hasOwnProperty` just above.
Fixes #1215
> Update extendObservableHelper for Typescript 2.6

- src/types/comparer.ts
- src/utils/utils.ts
- test/observables.js
There seemed to be an inconsistent behavior where NaN === NaN but deep NaN !== NaN.
I think @benjamingr talked with you about it. 
PR checklist:
> make deep NaN === deep NaN for computed values when using compareStructural

- src/utils/utils.ts
PR checklist:
_The implementation wasn't changed_
_Nothing of what the end user would notice_
_This change doesnt affect the public API_
_The implementation wasn't changed, only typings_
---
More strict `tools`/`objectAssign` typings:
- Allow extending object only by objects that `Partial`ly implements it.
- Guess type better when `objectAssign` is used for cloning an object.
Imagine we have an interface `Cat` and an object of that interface.
```ts
interface Cat { age: number; name: string; }
const fluffy = { age: 3, name: "Fluffy" };
```
If source is a `Partial<Cat>`, nothing is changed:
```ts
objectAssign(fluffy, { age: 4 }); // Okay. Fluffy's age was updated.
```
But if it is not, the error is thrown. We typically don't want Cats to stop being just Cats, do we?
```ts …
```
> More strict objectAssign typings

- CHANGELOG.md
- flow-typed/mobx.js
This is basically just copied from the typescript definition and slightly modified to match the flow syntax.
> improve flow typings for observable

- src/api/observable.ts
It seems the only reason to keep `IObservableFactories` as a class is to avoid declaring type definition and implementation separately. However, it does not seem to be entirely correct approach at runtime, because it's never expected that a new instance of `IObservableFactories` will be created. In addition, reading properties of prototype cause issues with some browsers.
Issue #1238
> Split `IObservableFactories` type definition and implementation

- CHANGELOG.md
- README.md
- flow-typed/mobx.js
- package.json
- test/flow/test.js
With this PR consumers can use the Flow type definitions without needing any configuration.
> correctly expose flow typings

- README.md
Provide more information in flow support section. 
https://github.com/mobxjs/mobx/pull/1254#issuecomment-354419598
> Update Flow support instructions

- docs/refguide/reaction.md
As long as I see the src code, I can invoke a reaction only once with this example. Is there any reason for being hidden?
> add example of reaction invoke once

- src/types/observablearray.ts
Hi! Currently, `IObservableArray<T>.find` returns `T` instead of `T | undefined` which leads to runtime errors.
I’ve tried to write a test, but it seems that `typescript-tests.ts` is not being typechecked, because even `var x:string = 1` doesn’t fail. Is there any way to test this?
> IObservableArray.find() typing fix

- src/api/autorun.ts
right now some of the when definitions return IReactionDisposer and others return Lambda, this pull requests makes both use IReactionDisposer
PR checklist:
> fix type definition for when

- CHANGELOG.md
- package.json
- src/api/flow.ts
- test/base/flow.js
- test/base/typescript-tests.ts
- test/tsconfig.json
- tsconfig.json
```javascript
const asyncFlow = flow(function * () { 
// do stuff
try {
yield Promise.resolve(3)
} catch (e) {
// cancel end's up here, e is "FLOW_CANCELLED"
throw e // now 'promise' will reject with "FLOW_CANCELLED"
}
})
const promise = asyncFlow()
promise.cancel() // rejects the next yield / return
```
Would you mind reviewing @benjamingr ? Does this approach make sense?
> introduced canceellable flows

- CHANGELOG.md
While upgrading from 2.6.0 to 2.7.0, I figured out that if people used `observable({ @computed get someProp()` in their code, reactions wouldn't happen leading to silent test failures and incredibly difficult to debug code. I added some notes to the CHANGELOG about this issue.
> Added something missing from the CHANGELOG

- src/api/flow.ts
The flow typing which accept generator with one and two parameters are returning `Promise` instead of `CancellablePromise`.
> Minor fix for flow typing

- docs/best/actions.md
Currently `flow` can't be used is decorator
> Docs: flow function docs fix

- CHANGELOG.md
- package.json
- src/api/computed.ts
- src/types/observableobject.ts
- test/base/babel-tests.js
So, back to declare-computed-props-on-instance-rather-then-prototype and hope stage 3 decorators come around quickly :)
Fixes #1396
> Fix issue where RN decorators didn't work

- CHANGELOG.md
- src/api/flow.ts
- src/api/observable.ts
- src/api/when.ts
- src/core/computedvalue.ts
- src/types/observablearray.ts
- src/types/observablemap.ts
- test/base/autorun.js
- test/base/babel-tests.js
- test/base/flow.js
- test/base/observables.js
- test/base/typescript-tests.ts
* Introduced `keepAlive` as option to `computed`
* All observable api's now default to `any` for their generic arguments
* Improved `flow` cancellation
* The effect of `when` is now automatically an action.
> Several improvements

- docs/refguide/object.md
Just a typo.  Updates `pase` to `pass`
> Docs: fix typo on object doc

- flow-typed/mobx.js
Updated the flow typings with the missing runInAction declaration.
> Flow-typed: add missing runInAction declaration

- src/core/spy.ts
- test/base/spy.js
Fix https://github.com/mobxjs/mobx/issues/1459
Making copy of `listeners` in `spyReport` can have performance impact so I changed unsubscribe action because it rarer event. Also all same listeners is removed with this change (not only first).
> Spy: fix stop listen from handler

- docs/refguide/api.md
Slightly better explanation of `disableErrorBoundaries` and inclusion of `_resetGlobalState` and a code example.
> Explain how to use disableErrorBoundaries and _resetGlobalState together

- docs/refguide/modifiers.md
Minor documentation fix for „geters“.
Compare e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
> Typo getters in modifiers documentation

- docs/refguide/api.md
- docs/refguide/computed-decorator.md
**I found these typos when I update the MobX Chinese Docs to V4.**
PR checklist:
> Docs: fix some typos

- src/api/flow.ts
this makes strict compilation error out
> add another missing import of `fail`

- src/core/computedvalue.ts
- test/base/babel-tests.js
Now the computed value will be reassign although the assignment was equivalent by the comparer.
@mweststrate 
Here is the [jsfiddle demo](https://jsfiddle.net/Kuitos/ycv4bb2a/15/) which describes the unexpected behavior, or u can check the added unit test for details🙂
> avoid the unnecessary reassign with the equivalent comparison result

- src/core/computedvalue.ts
The invariant check currently is checking *only* in production. That was not intended, so we change it to check when *not* in production.
> Fix invariant check for ComputedValue constructor

- src/api/object-api.ts
- test/base/object-api.js
> Update object api set to write through parent mobx administrator

- docs/refguide/autorun.md
It looks like the options section of the `autorun` docs were copied from the docs for `reaction`, and so include options that don't apply to `autorun`.
> Docs: Remove nonexistent options from autorun docs

- src/api/tojs.ts
- src/core/spy.ts
refactor: replace the memorizer from array to ES6 map in mobx.tojs() & extract the common cache method from recursion
PR checklist:
> refactor: replace the memorizer from array to ES6 map in mobx.tojs()

- src/api/computed.ts
- src/api/observabledecorator.ts
- src/utils/decorators2.ts
- test/base/decorate.js
This PR is to address #1454
The variant check is added to the property creator function. The caveat is that it throws when the target is initialized (even if the property being accessed is not the erroneous one).
Fixed random typos in comments that I came across.
> Throw error in development when @observable is used on getters

- src/types/observableobject.ts
- test/base/observables.js
The error described here: https://github.com/mobxjs/mobx/issues/1506 (Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@163] Error: [mobx] Property 'isIntersection' of '[object Object]' was accessed through the prototype chain. Use 'decorate' instead to declare the prop or access it statically through it's owner) is now a warning instead. 
On this PR someone should update the changelog, update docs and verify performance. Also _the warning comes up every time, there is no flag that checks if the warning was already printed_.
PR checklist:
> Changed illegal access error to a warning

- src/api/object-api.ts
- src/mobx.ts
- test/base/api.js
- test/base/object-api.js
PR checklist:
Still a WIP, looking at the best place to add the unit tests
> add entries method to observable object api [WIP]

- src/utils/utils.ts
I found that there is a tool function hasOwnProperty under utils/utils.ts that is not used to be redundant and that there is the same function in utils/eq.ts, has, should hasOwnProperty be deleted?
utils/utils.ts
const prototypeHasOwnProperty = Object.prototype.hasOwnProperty
export function hasOwnProperty(object: Object, propName: string) {
return prototypeHasOwnProperty.call(object, propName)
}
utils/eq.ts
function has(a: any, key: string) {
return Object.prototype.hasOwnProperty.call(a, key)
}
> Remove redundant code

- CHANGELOG.md
- src/core/computedvalue.ts
- test/base/observables.js
Fixes https://github.com/mobxjs/mobx/issues/1534
PR checklist:
> @computed({keepAlive: true}) no long calculates before being accessed

- README.md
Changed
> the **later** uses Proxies
to
> the **latter** uses Proxies
I'm not a native speaker, so probably someone should take a look at this — but as far as I can tell this is the correct spelling. 🙃
> docs: fix minor typo in readme

- test/base/typescript-tests.ts
Currently 2 tests are failing with TypeError on node 10 because Symbol.asyncIterator is defined and not writable. Sorry for removing PR template but it looked irrelevant to this small change.
> Do not reassign Symbol.asyncIterator in ts tests

- docs/best/devtools.md
Fixes typos in the Devtools documentation page.
`depenencies` => `dependencies` (typo)
`code-base` => `codebase` (widely accepted spelling)
> Docs: Fix typos in devtools.md

- docs/refguide/reaction.md
> Remove old api functionality from docs

- docs/best/pitfalls.md
> Warn against decorating @action.bound on componentWillUnmount()

- docs/refguide/api.md
isolatedGlobalState ==> isolateGlobalState
> Fix typo error

- docs/refguide/reaction.md
Hi, and thanks for the helpful documentation of MobX! :book: 
Reading the page on `reaction`, this paragraph seemed to be missing parts of a sentence describing the first argument given to the effect function. This commit rewords the paragraph somewhat to describe the first argument.
Making the PR to the `gh-pages` branch. Let me know if it should be directed at a different branch, or if you'd like some other changes.
> docs: Reword the effect function paragraph

- src/api/flow.ts
`flow` already supports async generators yielding Promises, just changing typings to allow it.
Also changing from `IterableIterator` to `Iterator`:
`IterableIterator` implements `Iterator` with the addition of `[Symbol.iterator]` property.
Because `mobx` does not use `[Symbol.iterator]` property, it's not necessary to use `IterableIterator`.
PR to support it in Mobx 4 - https://github.com/mobxjs/mobx/pull/1655
> Update typings to allow flow to take async generators - async function*

- src/api/flow.ts
`flow` already supports async generators yielding Promises, just changing typings to allow it.
Also changing from `IterableIterator` to `Iterator`:
`IterableIterator` implements `Iterator` with the addition of `[Symbol.iterator]` property.
Because `mobx` does not use `[Symbol.iterator]` property, it's not necessary to use `IterableIterator`.
> Update typings to allow flow to take async generators - async function* - MobX 4

- src/api/object-api.ts
- test/base/object-api.js
I went ahead and just did it, feel free to refute it if you believe that the change shouldn't be made.
If you're willing to accept it, should I add an entry to the changelog?
PR checklist:
> Add support for obs. arrays on `keys`. Fixes #1600

- docs/README.md
- docs/best/devtools.md
- docs/intro/overview.md
- docs/refguide/action.md
- docs/refguide/autorun.md
- docs/refguide/computed-decorator.md
- docs/refguide/observable-decorator.md
- docs/refguide/observable.md
- docs/refguide/observer-component.md
- docs/refguide/when.md
- adds egghead lesson embeds in place of links
<details>
<summary>Screenshot of section closed</summary>
<br>
</details>
<details>
<summary>Screenshot of section open with Embed showing</summary>
<br>
</details>
> adds egghead video embeds to docs

- docs/best/store.md
The proceeding pages in the guide are unrelated.
> Remove reference to "components and actions" in next section

- src/api/action.ts
- src/api/observabledecorator.ts
- test/base/decorate.js
Same issue #1448, new case.
---
PR checklist:
> Decorate: Allow modifier when strict

- src/api/action.ts
- src/api/observabledecorator.ts
- test/base/decorate.js
Same issue #1448, new case.
---
PR checklist:
> Decorate: Allow modifier when strict (MobX 4)

- src/mobx.ts
update for prevent error when rollup-plugin-commonjs is used
> Prevent rollup from breaking on `process.env.NODE_ENV`

- src/api/tojs.ts
- test/base/tojs.js
PR checklist:
-----
`toJS` will recursively convert an object containing Mobx observable value into a plain object
> Refactor toJS

- src/api/tojs.ts
- test/base/tojs.js
PR checklist:
-----
`toJS` will recursively convert an object containing Mobx observable value into a plain object
> Refactor toJS for mobx4

- docs/refguide/observer-component.md
Hey, great job with mobx! Just started using it today and am really liking it!
Just stumbled across this typo in the docs, a missing `/`.
Should I add this to the changelog as well or is it small enough not to matter?
Cheers!
---
* ~[ ] Added unit tests~
* ~[ ] Updated changelog~
* ~[ ] Added typescript typings~
* ~[ ] Verified that there is no significant performance drop (`npm run perf`)~
> Fix typo in docs/refguide/observer-component

- flow-typed/mobx.js
Add  "never", "always" and "observed" possible values to enforceActions configuration parameter.
It's because true, false and "strict" now deprecated.
> Add  "never", "always" and "observed" to enforceActions

- src/types/observablearray.ts
I added minor missing types that I found useful when developing with `mobx+ts` for the first time
```
PR checklist:
```
> Minor types added

- docs/refguide/autorun.md
The current documentation says that the function passed to autorun will receive a disposer function as it's only argument, but the examples show the disposer being returned by autorun.  Experimentation has shown the examples to be correct, so this fixes the docs to match.
> Clarify autorun disposer

- src/api/computed.ts
- test/base/babel-tests.js
- test/base/typescript-tests.ts
See #1777, computed properties are now always declared on the instance, rather than on the prototype. Solves some hot reloading issues. Reverts to original MobX 3 behavior
> Fixed stack overflow for @computed on RN, fixes #1777

- docs/best/decorators.md
The link pointing to customize-cra was incorrect. This updates the link to the correct one.
> Add correct link to customize-cra

- CHANGELOG.md
- src/types/observablearray.ts
- test/base/array.js
This PR fixes #[1839](https://github.com/mobxjs/mobx/issues/1839).
There is also a [PR](https://github.com/mobxjs/mobx/pull/1840) for mobx@4.
No need for docs, typings, performance.
> Fix array dehance (#1839)

- package.json
I've been running into issues with basic usage of mobx, where in a complete esm environment, a `import * as mobx from 'mobx'` webpack would still require the cjs version of mobx, though, a `module` entry is there and also defined within the `package.json`. This caused a lot of headache, as there was no reason to do so.
However, due to some weird behaviour, webpack 4 refuses to load the module version of mobx, until I've added the `browser` field to `package.json`. 
Everything should still work correctly within a commonjs environment, as a require call to mobx within the browser still requires the cjs version. Thanks a lot to https://github.com/stereobooster/main-module-browser-test for the idea behind this.
This works reliable for me, so it would be great to get this merged in!
> support cjs and esm version for browser builds

- src/api/flow.ts
See: https://github.com/mobxjs/mobx/issues/1816
> Improve flow() typing

- src/mobx.ts
PR checklist:
To fix #1548, I add a simple env variable to force mute the warning in this PR. I wonder is it necessary to add it's usage to docs (as it may be rarely used) 😆
> fix: add a configure env variable to mute minification warning (fix #1548)

- src/api/become-observed.ts
- src/core/atom.ts
- src/core/computedvalue.ts
- src/core/observable.ts
- test/base/extras.js
PR checklist:
This PR is to fix #1537, in `become-observed.ts`, there is a shared object to store the `onBecomeObserved` and `onBecomeUnobserved` for each Atom instance by name. Each Set of the hook of an atom will be initialized only when `onBecomeUnobserved` or `onBecomeUnobserved` invoked. So I think there's no harm to the performance.
Looking forward to your opinion 😆
Special thanks to #1771
> fix: earlier onBecome(Un)Observed disposer will not dispose later listener (fix #1537)

- docs/refguide/computed-decorator.md
The code was broken, it obviously needed a `.box`;
> gh-pages: Fix an error in example code

- tsconfig.json
This is required for the recent demo of cross-repo linking to mobx
See https://twitter.com/mweststrate/status/1074609242521436160
> Add compilerOptions.rootDir=src setting to tsconfig.json

- docs/refguide/array.md
Faux arrays don't play nicely with native methods like concat. Updated docs.
> Add clarification about faux-arrays

- docs/best/pitfalls.md
```diff
- MobX computeds will automatically be kept alive during transactions as well, see PRs: [#452](https://github.com/mobxjs/mobx/pull/452) and [#489](https://github.com/mobxjs/mobx/pull/489)
+ MobX `computed`s will automatically be kept alive during transactions as well, see PRs: [#452](https://github.com/mobxjs/mobx/pull/452) and [#489](https://github.com/mobxjs/mobx/pull/489)
```
```diff
- To force computed values to stay alive one can use the `keepAlive: true` option, but not that this can potentially create memory leaks.
+ To force computed values to stay alive one can use the `keepAlive: true` option, but note that this can potentially create memory leaks.
```
Also noticed this: “around” was misspelled, but I left it untouched as it sounded funnier that way 😆
> So if you fiddle …
> Fix typo in `pitfalls.md`

- src/types/observablearray.ts
- src/types/observablemap.ts
- src/types/observableset.ts
- src/utils/iterable.ts
Fixes #1878, an omission in Set backport. Reuses existing utils. Should restore IE11 compatibility.
> Polyfill symbols in set, map and array alike

- docs/refguide/reaction.md
Just a tiny change from "then" to "than" to be grammatically correct.
> Fix grammar

- flow-typed/mobx.js
This improves flow types. `when` and `reaction` return a disposer function. The disposer function does not return anything: `() => void` (as seen eg [here](https://github.com/mobxjs/mobx/blob/6df2f5afe9d8b857fb13fa8d6e789a3c3eb523d1/src/core/reaction.ts#L176))
the previous definition was `() => mixed` which is better than `any` (that was there before) but it is not correct
> fix flow types

- docs/best/decorators.md
Was kinda broken till 2.1.1.
Reference:
https://stackoverflow.com/questions/53096300/how-can-i-enable-decorators-support-when-running-tests-with-cra-2-1
PR checklist:
> CRA 2.1 came with decorator support OOTB.

- src/api/object-api.ts
- src/types/observableset.ts
- src/utils/eq.ts
- src/utils/utils.ts
The original implementation and the backport made use of Array.from.
Mobx4 appears to avoid the usage of Array.from by instead using its
internal iteratorToArray function. All Array.from calls have been
replaced by iteratorToArray calls.
Also, IE11 lacks the "values" function on Sets,
and even ObservableSet.toString ended up depending on it.
A workaround has been implemented that allows the
ObservableSet.values to work even in IE11.
> Make ObservableSet backport compatible with IE11

- src/types/observablemap.ts
- src/types/observableset.ts
This PR fixes (restores) the return type of the `Symbol.toStringTag` method of observable maps and sets to return either `"Map"` or `"Set"`.
This fixes the following TypeScript errors:
```
error TS2416: Property '[Symbol.toStringTag]' in type 'ObservableMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
Type 'string' is not assignable to type '"Map"'.
```
```
error TS2416: Property '[Symbol.toStringTag]' in type 'ObservableSet<T>' is not assignable to the same property in base type 'Set<T>'.
Type 'string' is not assignable to type '"Set"'.
```
See https://github.com/mobxjs/mobx/commit/4a65b504eb67a79f9935985201f57438dfbeb972 for parts of changes causing this error.
Current workaround is to use `4.9.1` where this regression was not present.
> Fix toStringTag return type for observable Maps and Sets

- CHANGELOG.md
- src/types/observablemap.ts
- test/base/map.js
- Not clear what the 'right' way to do this is, seems lots of PRs ignore it? I've added an 'Unreleased' section ready to rename for the next release for now.
- No changes necessary imo
- No types have changed
---
@mweststrate you mentioned `safeStringify` in #1925, I couldn't find that - looks like it's [a function in the mobx-state-tree codebase](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/type/type-checker.ts#L38-L45)?
I've written a separate key stringification function instead. Here it actually doesn't use JSON.stringify, because JSON can't represent symbols, and [they're normally omitted from JSON stringified objects](https://esdiscuss.org/topic/json-stringify-and-symbols). For the same reason, I've also preserved symbol-ness in `toPOJO` …
> Allow Symbol keys in observable maps (fixes #1925)

- README.md
Google's crawler doesn't support Proxy and thus JS will throw when it crawls an app running MobX 5+. This leads to poor or non-existant indexation, disturbances in the Google Developer Console (can't crawl as Google, or use features that really on a successful crawl).
I think it's worth mentioning here because it can be a bigger problem than just not supporting IE11 and old Node versions for some people.
> Update README - Google's crawler

- CHANGELOG.md
- src/api/object-api.ts
- src/types/observableset.ts
- test/base/object-api.js
> add 'set' support for observable sets

- README.md
See [Google announcement](https://webmasters.googleblog.com/2019/05/the-new-evergreen-googlebot.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+blogspot%2FamDG+%28Official+Google+Webmaster+Central+Blog%29)
> Update README -- Googlebot now runs Chrome 74!

- docs/refguide/computed-decorator.md
Markdown code for link was wrong.
> [docs] Fix typo in link

- src/types/observablearray.ts
I just noticed that array "splice" would return the array proxy as object, yet "update" would return the array itself
This PR fixes that
> fix update array event using this as object instead of proxy

- docs/refguide/api.md
I changed words for more consistency.
`propertyMap` => `properties`
`props` => `properties`
> Fix: extendObservable docs on api.md

- src/api/observable.ts
fixes TS typings for this case
```
const obsSet: ObservableSet = observable(new Set<any>())
```
> fix TS for observable set

- flow-typed/mobx.js
We're updating our MobX to version 4 at Coinbase. We came across an issue with the flow typings for `PropertyDescriptor`. The first commit is us just running prettier. The second commit is where we bring in the Flow core definition of `PropertyDescriptor`.
Can we make sure this is released under version 4?
> Updated PropertyDescriptor type to use the latest flow core definition

- src/api/computed.ts
- src/api/extendobservable.ts
- src/api/object-api.ts
- src/api/observabledecorator.ts
- src/api/tojs.ts
- src/types/dynamicobject.ts
- src/types/observablemap.ts
- src/types/observableobject.ts
- src/utils/decorators.ts
- src/utils/utils.ts
- test/base/object-api.js
- test/base/tojs.js
Hey folks, 
I was recently stuck trying to figure out why my observable properties weren't working with Symbols as keys. Then I found #1809 & #1925.
In this PR I hope to get things kicked off. Being new to the codebase there are probably thing's I've missed.
* Please let me know if I've gone about it the wrong way
* Or, there are still more tests and types to write
I've also tested this is a mid size production app.
---
PR checklist:
> Support Symbol named observable properties

- src/types/observablearray.ts
- test/base/intercept.js
Apparently my fix to send the array proxy in the update event wasn't ok.
I didn't take into account that "set" is called with the actual proxied array as "this", therefore adm.proxy has to be used instead
Without this fix change.object in array update events is set to "undefined" :-/
> Fix array update proxy (important fix)

- src/api/computed.ts
- src/api/extendobservable.ts
- src/api/object-api.ts
- src/api/observabledecorator.ts
- src/api/tojs.ts
- src/types/observablemap.ts
- src/types/observableobject.ts
- src/utils/decorators2.ts
- src/utils/utils.ts
- test/base/object-api.js
- test/base/tojs.js
I backported symbol support from MobX 5 to MobX 4, without thinking it really through. Although symbols could potentially be used in practice, this probably misses the point that mobx 4 is used in more backward compatible modi, and didn't require polyfills as of yet. 
This PR reverts symbol support. A downside of this PR is that this increases the semantical difference between mobx 4 and 5
Fixes #1986, #1987
> Revert mobx 4 symbol support

- src/api/configure.ts
- src/core/globalstate.ts
- src/types/observableobject.ts
- test/base/strict-mode.js
We ran into a problem where we couldn't overwrite computed properties in tests. Some of our computed properties are very complicated and it would be easier to just overwrite them in tests rather than overwrite the depending properties. 
This fixes https://github.com/mobxjs/mobx/issues/1888 and https://github.com/mobxjs/mobx/issues/1867
PR FOR MOBX 4 https://github.com/mobxjs/mobx/pull/2011
> Allow overwriting computed values if configured (MobX 5)

- package.json
- src/api/configure.ts
- src/core/globalstate.ts
- src/types/observableobject.ts
- test/base/strict-mode.js
We ran into a problem where we couldn't overwrite computed properties in tests. Some of our computed properties are very complicated and it would be easier to just overwrite them in tests rather than overwrite the depending properties. 
This fixes https://github.com/mobxjs/mobx/issues/1888 and https://github.com/mobxjs/mobx/issues/1867)
PR FOR MOBX 5
> Allow overwriting computed values if configured

- src/api/extendobservable.ts
use regular `for` on array of keys
seems that it caused bugs in v5.10 (in my case I was extending the Array prototype with enumerable properties, and those properties were iterated because of `for i in keys`. 
can add a test, not sure where is the right place or if it's required for such a small change.
> fix(extendObservable): use regular `for` on array of keys

- docs/best/pitfalls.md
There were a few redundant calls that made it hard to understand.
> Fix display name pitfall example

- docs/refguide/computed-decorator.md
#356
Added "Computed values run more often than expected" part to computed docs. It links to the corresponding part of the pitfalls page.
> docs: link to pitfalls section from computed

- src/types/observablemap.ts
- test/base/map.js
fixes #2031
* ~Updated docs (either in the description of this PR as markdown, or as separate PR on the `gh-pages` branch. Please refer to this PR). For new functionality, at least [API.md](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md) should be updated~
* ~Added typescript typings~
> Use onBecomeUnobserved for ObservableMap._hasMap garbage collection

- flow-typed/mobx.js
Flow 103 throws an error on the current mobx types (see #2048). This is a simple fix (we just mirror the change Flow made).
I'd like to get this released sooner than later because this issue is a blocker for every Mobx user that also has Flow as a dependency 🙏 
PR checklist:
> Fix flow definition for Flow 103

- .github/lock.yml
Adding a stale bot (#2015) was surely a good step. Let's take it further and add the [lock bot](https://github.com/apps/lock) as well. People tend to comment on long-closed issues. It's a bad habit as nobody else except those who participated (or watching a whole repo) can't see such a comment.
I've used pretty much default config except I've set 60 days for locking closed issues. I've excluded pulls.
All we need now is to enable the app which I don't have permission to do.
> Setup the lock bot

- docs/refguide/computed-decorator.md
Just a small update for the docs. On the page about `@computed`, they import `computed` from `mobx` but in the code below, the `computedFn` from `mobx-utils` is used instead. So I'm just fixing the imports.
PR checklist:
> Fixing import in the example

- CHANGELOG.md
- src/types/observablemap.ts
- src/utils/utils.ts
- test/base/map.js
> fix issues 1980 and 2003

- CHANGELOG.md
- README.md
Notes about iOS 9, RN 0.59 and new Hermes runtime.
> Сlarify React Native runtime support

- CHANGELOG.md
- src/types/observablemap.ts
- src/utils/utils.ts
- test/base/map.js
Reverts mobxjs/mobx#2057 due to unresolved issues discussed at #2058
> Revert "fix issues 1980 and 2003"

- docs/refguide/observe.md
Fix typo _where_ instead of _were_
> observe.md typo

- package.json
- yarn.lock
Motivation:
yarn is actually missing automatic dedup of deps,
Which leads to multiple-but-compatible versions of deps.
[yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) is a complementary tool to solve that. 
It's recommended to run it after any dependencies add/remove/upgrade
Related:
https://github.com/yarnpkg/yarn/issues/3778
(And there are more issues around yarn repo related to that)
> chore: Add & apply yarn deduplicate

- package.json
- yarn.lock
Reverts #2078 by @Bnaya and the `yarn-deduplicate` is used with NPX instead of having it in direct deps which is unnecessary for something like that.
As a side effect, now we can actually see (in that separate 2nd commit) what has that tool done and apparently it's not such a huge problem as it it's claimed to be :)
> Use yarn-deduplicate with NPX

- docs/best/react.md
PR checklist:
****
I forked mobx just before to contribute many thing forward.
I fixed spellings.
I don't know if you need or not, but I think better it has right spelling.
Thanks.
> correct spellings

- src/core/globalstate.ts
- src/types/observablearray.ts
Fixed three instances where "suppressed" was incorrectly spelled "supressed", two of which are user-facing.
> Use correct spelling of "suppress"

- CHANGELOG.md
- src/core/action.ts
- src/core/globalstate.ts
- src/mobx.ts
- test/base/action.js
- test/base/api.js
Basically adds a new `startActionWithFinisher` method that allows someone to start/finish an action without needing a code block.
This is mostly useful for library creators, and probably for a future async pattern I'm investigating that doesn't rely on generators in order to get better typings in TS.
Basically on this pattern, an asyncAction would go something like this:
```ts
const myAsyncAction = asyncAction("name", async(x) => {
// the wrapper starts the action using startActionWithFinisher
// currentActionContextFinisher = startWithActionFinisher(...)
// some mutating actions
const data = await _(getDataFromBackend(x))
// more mutating actions
// the wrapper try/catches the whole async block, runing currentActionContextFinisher(true) if
// throwing, (false) if not
}
// decorator …
```
> expose startAction and endAction

- CHANGELOG.md
- flow-typed/mobx.js
- src/api/autorun.ts
- src/api/configure.ts
- src/api/when.ts
- src/core/action.ts
- src/core/derivation.ts
- src/core/globalstate.ts
- src/core/observable.ts
- src/core/reaction.ts
- test/base/autorun.js
- test/base/autorunAsync.js
- test/base/reaction.js
- test/base/strict-mode.js
> feat: derivationRequiresObservable & observablesRequiresReaction

- flow-typed/mobx.js
followup for #2079, update flowtypes
> docs: polish/add flowtype for requiresObservable

- docs/refguide/api.md
> Docs for #2079

- docs/refguide/action.md
Hi, it seems that there are some dead links in the documentation about `action`.
Please check out these pages
https://mobx.js.org/refguide/action.html#action
https://mobx.js.org/refguide/action.html#when-to-use-actions
So, I would like to fix this.
> Fix dead links in docs about Action

- README.md
- docs/README.md
The obsolete section about card donations leading to a non-existing page. Since OpenCollective is preferred, let's keep it less confusing :)
@mweststrate I also wonder, those list of backers/sponsors is generated somehow? If not, there might be some people missing, right?
> Remove obsolete donation info

- docs/refguide/observable-decorator.md
The page title for the @observable page in the "Making Things observable"-section was missing an 'r'.
Thanks for the wonderful work that you all do :raised_hands:
> Docs: Fix title of "@observable" page

- CHANGELOG.md
- docs/refguide/api.md
- docs/refguide/computed-decorator.md
- src/utils/comparer.ts
- src/utils/eq.ts
- test/base/extras.js
Fixes https://github.com/mobxjs/mobx/issues/1561
Adds comparer.shallow for shallow comparisons of objects/arrays
Will do a backport when/if accepted
> Shallow comparer

- src/core/action.ts
- src/core/globalstate.ts
Backport of https://github.com/mobxjs/mobx/pull/2136
> Fix for #2135 (mobx4)

- CHANGELOG.md
- src/types/intercept-utils.ts
- test/base/intercept.js
Currently, when disposing an interceptor within the provided callback, mobx throws an error stating that `interceptors[i] is not a function`. With this PR it will continue the execution by cloning the interceptors array before the execution loop.
Fixes #1950 
PR checklist:
> Fix error when interception is removed in intercept (#1950)

- CHANGELOG.md
- package.json
Changes `postinstall` to `prepare` for website dependency install. Bumps to 5.14.2 so this can be republished, and added changelog entry.
Fixes #2165
> Fix 2165 use prepare

- CHANGELOG.md
- flow-typed/mobx.js
This fixes flow typings for flow() which are now fundamentally broken. Flow() returns a cancellable promise (fixed) and a signature that is not valid was removed. 
usage,  if the suggestion from https://github.com/mobxjs/mobx/pull/2164#issuecomment-544466503 is accepted
```js
// @flow
import { flow, type CancellablePromise } from 'mobx';
export class FlowTest {
promise: CancellablePromise<string>;
constructor() {
this.promise = this.fetchSomeString(2);
this.promise.cancel();
}
fetchSomeString = flow<string, number>(function*(pageNumber: number) {
try {
const projects = yield this.fetchStringSomehow(pageNumber);
return projects;
} catch (error) {
return '123';
}
});
fetchStringSomehow = (pageNumber: mixed): Promise<string> => {
console.log(pageNumber);
return Promise.resolve('123');
};
} …
```
> fix Flow typings for flow()

- flow-typed/mobx.js
> fix Flow typings for flow() - mobx4

- docs/best/pitfalls.md
changed [dead What will Mobx react to link](https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/react.md#mobx-only-tracks-data-accessed-for-observer-components-if-they-are-directly-accessed-by-render) to [https://mobx.js.org/best/react.html](https://mobx.js.org/best/react.html)
> Update 'What will Mobx react to' Link

- CHANGELOG.md
- src/core/globalstate.ts
currently `getGlobal` is first invoked from an iife which initializes `globalState`, which means `mockGlobal` is not yet initialized.
PR checklist:
> allow mobx to run in web worker

- CHANGELOG.md
- docs/best/actions.md
- flow-typed/mobx.js
- src/api/flow.ts
- src/mobx.ts
- test/base/api.js
- test/base/flow.js
This exports FLOW_CANCELLED because it's a little unusual to have to introduce the constant to our code base instead of importing it from mobx.
> cancelled flow() to reject with new FlowCancellationError

- CHANGELOG.md
- src/api/observable.ts
- src/utils/decorators.ts
- test/base/typescript-tests.ts
Resolves #2159 
1. I added a new test in `typescript-tests` that tries to use computed property keys... see test `#2159 - computed property keys`. Please validate this test is a supported use case (I think it is). It was failing before this change (see original issue for details). By the way, I verified the test passes if the key isn't a computed symbol to make sure the test itself is true.
2. Changed `decorators.ts` and `observable.ts` to apply their logic to symbol keyed properties in addition to string keyed properties.
PR checklist:
I don't think this fix needs any doc updates.
As all changes were made in TS files, no need.
Note: I didn't see `npm run perf` but I tried out `npm run test:performance`
Current develop branch: 66.22 real        67.58 user
This PR: 62.46 real        63.76 …
> Observable decorator on computed symbol keys

- website/static/getting-started.html
The "getting started" documentation page has the example code just return the first todo, whenever it logs the "next item". Instead, it should search for the first todo item that is not yet completed.
Screenshot of old behavior (which doesn't make sense, in code or in what is displayed):
> Getting Started: Fixed that "get next item" just returns first item!

- CHANGELOG.md.orig
- src/core/derivation.ts
Followup for #2196
quickfix for #2196. 
#2196 is not released yet
https://github.com/mobxjs/mobx/commit/e21b812cd1ed426840f8c7e45e07ec195c40f04c#r35912870
> fix: missing allowStateReadsEnd on exception branch

- flow-typed/mobx.js
I somehow forgot to add this in https://github.com/mobxjs/mobx/pull/2190/files
this is the same as https://github.com/mobxjs/mobx/pull/2203 but the change how `FlowCancellationError` is implemented is not needed in mobx 4 branch, since it's already done this way in mobx 4.
> add FlowCancellationError to Flow typings

- flow-typed/mobx.js
- src/api/flow.ts
in some environments, `isFlowCancellationError()` will return false even if it should return true. This change is already present in the mobx 4 branch, as seen here https://github.com/mobxjs/mobx/pull/2190/files because the tests were failing without it. On master, different impl is used, as mentioned in https://github.com/mobxjs/mobx/pull/2172#issuecomment-551166733.
Also added forgotten typings for FB's Flow
> do not extend Error for FlowCancellationError

- src/api/action.ts
Fixes: https://github.com/mobxjs/mobx/issues/2211
I prepared the links to TS playground with multiple test cases so you can verify that type inference works now.
[Example 1](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQEFsYEIk4BvAXwChbRJZEU0tcDjTyAxHGaAE8qtOGLgB6CXCSYAtsAA2wAM4q4-MkhWjxAHkIBGADRwASqYAqcUKiQATdQApMhgFxwjASjgBeAHzm-k7oSB6WXuFwAGScJFq6YgYmngBMphZw1rbADs6uHkammKmFqT4BQSFhWZFZMXHcSIlwyaaE6Z4AzBlWNiB2jnAu7p4pJWXFXYVdFYFmwaHhddaxRPHkLW1p7T2eACy99Tl5wwVjxaU7GtPdxfuF+3NVS7VRa1wJ4q1F14R7hEOngArEdsgNckMRoVxlcOlMZvdHsVgYVgc8FtVlu8Wt91k0tr94XcDu1QZ4AGxg-qDfKjX4Ta6YW7-JGkjQUwoUjGLGoRHHfPGfTYtKQyeTAewaDbaQkpTLg2lnemGHlOWQKDwqGBQZAAc1Mr359Q+Mrl7U6CppkLpMMuZTVGuAWp1+sNfJWDXxX30RM6rPMfROUPODLhnWZM0dEpduqQBrgRs9poJ322xIDgOpwdtFw04YRJMwDwO0c1cG1cYTSYFgrE3s2ab9u3aQMI …
> Fix type inference of the action callback arguments

- package.json
- test/base/typescript-tests.ts
- yarn.lock
As discussed in https://github.com/mobxjs/mobx/pull/2213 we decided to add TS type tests to prevent typing regressions in the future. Currently, tests are failing because types of the action callback arguments are inferred incorrectly: they are all converted to 'unknown' type. This fix https://github.com/mobxjs/mobx/pull/2213 will make tests pass.
> Type tests for the action callback arguments

- README.md
- docs/README.md
remove links pointing to migrated docs
Part of the mobx docs had been moved to [Awesome mobx](https://github.com/mobxjs/awesome-mobx#awesome-mobx), which leads to navigation to non existing pages.
> fix broken links

- website/static/getting-started.html
Getting started linked mobx-devtools, but it marked as obsolete in repo, also mobx changelog for v6 says few words about it and ives some recommendations, which I used to update the docs.
> updated obsolete devtools info based on changelog

- src/types/observableset.ts
`ObservableSet` doesn't need to change the initial values array, so it makes sense to allow passing in a `readonly` one.
> Make initial values of observable set accept readonly array

- src/utils/eq.ts
- test/base/extras.js
From: https://github.com/mobxjs/mobx/issues/2237
Adds these test:
```js
expect(sh(new Set([1, 2]), new Set([1, 2]))).toBe(true)
expect(sh(new Map([[1, 2]]), new Map([[1, 2]]))).toBe(true)
```
which fails.  The rest of the changes are to make it pass.
Note that this PR is a superset of the changes from #2240.
I have only prepared a minimal proof-of-concept to illustrate the issue and propose a fix.  I can add more thorough tests after some initial feedback.  I'm also happy for someone else to take this over if they prefer.
> supports ES6 Sets and Maps in shallow comparer.

- CHANGELOG.md
- docs/refguide/api.md
- src/api/extendobservable.ts
- test/base/extendObservable.js
- test/base/makereactive.js
- test/base/observables.js
- test/base/proxies.js
- test/base/typescript-tests.ts
Currently extendObservable throws an error if you try to use it on a property which already exists in the target object/class. This makes it impossible to dynamically make an existing property observable.
> extendObservable: remove constraint for existing property

- src/api/extendobservable.ts
- test/base/extendObservable.js
- test/base/makereactive.js
- test/base/observables.js
- test/base/typescript-tests.ts
Same as https://github.com/mobxjs/mobx/pull/2252 but for mobx4.
> extendObservable: remove constraint for existing property for mobx4

- src/v4/core/action.ts
- src/v5/core/action.ts
- test/v4/base/action.js
- test/v5/base/action.js
> Define action name to be as the function name

- package.json
- scripts/build.js
Fixes #2266 #2264 
Here is the build output it creates, looks ok to me, but I could use a second pair of eyes.
[v5.zip](https://github.com/mobxjs/mobx/files/4117954/v5.zip)
cc @mweststrate @ranyitz @le0nik
> Handle process.env correctly in build

- src/v5/types/observablemap.ts
- test/v5/base/map.js
Oversight in fix for #940, delete wasn't reporting in strict mode.
> fix: ObservableMap.delete should respect strict mode

- src/v4/api/object-api.ts
- src/v4/types/observablemap.ts
- src/v4/types/type-utils.ts
- test/v4/base/map.js
- test/v5/base/map.js
Replaced `Array.from`
Replaced `for of`
Contains fix/test #2275
Added few generic tests.
> ObservableMap - replace _keys array with _keysAtom

- src/v4/types/observablemap.ts
- src/v4/utils/utils.ts
- src/v5/types/observablemap.ts
- src/v5/utils/utils.ts
- test/v4/base/map.js
- test/v5/base/map.js
Fixed #2253 
Fixed #1980 for V5 (it was fixed for V4)
Synced V4/V5 map tests.
Fixed deprecation warnings in V4 test.
Removed invalid use of `Object.entries` in V4 (`convertToMap`)
> fix: map.replace #2253 (interceptors) #1980 (key order V5) 

- package.json
- yarn.lock
This is the alternative approach to #2291 which Michel pointed out is used in Immer. It's basically a faster variant of `lint-staged`. It could use some improvements, but it already looks fairly good.
Let's give it a try in the wild. I am not going to wait for approval as it shouldn't break anything. I made PR mostly so everyone is aware of this change.
Closes #2291
> Use pretty-quick instead of lint-staged

- src/v4/types/observablemap.ts
- src/v5/types/observablemap.ts
- test/v4/base/map.js
- test/v5/base/map.js
Reuses existing iterator instead of converting it to array first.
Added test for #2112, which was already fixed, most likely by #2279 (for V4)
Types may need some adjustments, help welcome :)
> Improve map.values/entries perf + add test for #2112

- CHANGELOG.md
- src/v4/api/computed.ts
- src/v5/api/computed.ts
- test/v4/base/decorate.js
- test/v5/base/decorate.js
Hello. As suggested by @jefffriesen in #1867, this pr adds better error text in case of missing getter when using decorator syntax.
-   [x] Updated changelog
> Report better error for missing decorated getter #1867

- docs/refguide/api.md
- docs/refguide/autorun.md
- docs/refguide/reaction.md
Default scheduler for `reaction` and `autorun` is actually **throttling** the execution even though in the documentation it says it's **debouncing**. There is a big difference between the two, and I think the documentation should reflect that.
There is an issue opened because of this confusion: https://github.com/mobxjs/mobx/issues/1956
[throttle vs debounce example reminder](http://demo.nimius.net/debounce_throttle/)
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2337"><img src="https://gitpod.io/api/apps/github/pbs/github.com/ivandotv/mobx.git/b04ce422 …
> replace word debounce with throttle in the documentation

- docs/assets/getting-started-assets/javascripts/react-with-addons.js
There is a small typo in docs/assets/getting-started-assets/javascripts/react-with-addons.js.
Should read `occurred` rather than `occured`.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2338"><img src="https://gitpod.io/api/apps/github/pbs/github.com/timgates42/mobx.git/ddf2c3f319ad2c49e7dd22e41e01dc8e7aa57a7e.svg" /></a>
> docs: Fix simple typo, occured -> occurred

- CHANGELOG.md
- src/v4/types/observableset.ts
- test/v4/base/set.js
- test/v5/base/set.js
It appears that there's a missing `reportObserved` on the `forEach` method within `ObservableSet` in mobx 4.x. This makes it non-reactive. Verified that 5.x is working as intended.  
Issue can be reproduced here: https://codesandbox.io/s/mobx-set-foreach-broken-t8bjg
```javascript
import { observable, autorun } from "mobx";
const set = observable(new Set());
autorun(() => {
set.forEach(v => console.log(v));
});
set.add("bar"); // won't run
set.add("foo"); // won't run
```
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2341"><img src="https://gitpod.io/api/apps/github/pbs/github.com/melnikov-s/mobx.git/f8667c7ee4fbb9ffdf5130ae9c1c631055c803be.svg" /></a>
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2341"><img …
> Fix for ObservableSet.prototype.forEach being non-reactive in 4.x

- docs/refguide/computed-decorator.md
This PR adds some paragraphs around computed caching and memoization that seem to be a stumbling block for new users of Mobx. I have been using Mobx for a few years coming from other derived data layers and this was never explicitly clear to me.  The use of the `get` keyword in example code with intention of not using the method as a getter is unintuitive.
I had to ask for clarification about this on stackoverflow: https://stackoverflow.com/questions/61129530/mobx-how-to-cache-computed-values
and then pieced together tidbits from https://github.com/mobxjs/mobx/issues/356
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2329"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kevzettler/mobx.git/002450e75a7a0b4d8bccd5b3435cb0f70df4011b.svg" /></a>
> Add memoization and getter access documentation

- CHANGELOG.md
- src/v4/types/observablearray.ts
- src/v5/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
additionally:
Possibly fixed `find`, `findIndex`, `includes` not being reactive in V5
Added support for `flatMap`/`flat` in V5
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2348"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/b5784daf1aba927c30e54abb67cc1f5c50fc7c61.svg" /></a>
> Fix #2326  pass correct array to callbacks

- docs/best/store.md
Docs-only change.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2408"><img src="https://gitpod.io/api/apps/github/pbs/github.com/jamonholmgren/mobx.git/c69ef3f732133a1226c900e1ede285b0e1b3ef1f.svg" /></a>
> Replaces jQuery with vanilla JS in store example

- src/types/observableobject.ts
I made the PR to cache getKeys() of ObservableObjectAdministration. 
When I run `yarn test`, the program hit the cache 91 times.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2410"><img src="https://gitpod.io/api/apps/github/pbs/github.com/MoonBall/mobx.git/3b93bd0fdd70ebd8b21ea8cae02c1da39f0e7101.svg" /></a>
> cache getKeys() of ObservableObjectAdministration

- CHANGELOG.md
- src/v4/types/observablearray.ts
- src/v5/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
Fix for: https://github.com/mobxjs/mobx/issues/2423
~~Missing test for `flat/flatMap`, not sure how they're supposed to behave.~~
EDIT: Dehancer is responsible for nested arrays, see the test how it's handled.
Once it's merged I will take a look at V6
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2426"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/2261440c3fbdd2e38d92c08f64560c4b55ee5111.svg" /></a>
> fix array methods not dehancing

- src/v4/types/observablemap.ts
- src/v4/types/observableset.ts
- src/v5/types/observablemap.ts
- src/v5/types/observableset.ts
- test/v4/base/observables.js
- test/v5/base/observables.js
fix: observable canot be created when enforceActions is `always` https://github.com/mobxjs/mobx/issues/2424
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2425"><img src="https://gitpod.io/api/apps/github/pbs/github.com/mobxjs/mobx.git/a91da70da8509201c94cfdabcb5bc65f23c576ff.svg" /></a>
> fix: observable canot be created when enforceActions is `always` #2424

- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/src/undecorate.ts
fix https://github.com/mobxjs/mobx/issues/2415.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2429"><img src="https://gitpod.io/api/apps/github/pbs/github.com/mobxjs/mobx.git/9be3a0ceea598e78d9ad9ec81cdf3e1168b04a73.svg" /></a>
> fix: makeObservable gets added to the type import

- src/v4/api/action.ts
- src/v4/api/computed.ts
- src/v4/api/observable.ts
- src/v5/api/action.ts
- src/v5/api/computed.ts
- src/v5/api/observable.ts
Closes #2438
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2439"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Amareis/mobx.git/10aaf6d5099c529882e8ebb2a119cd63688a63a1.svg" /></a>
> FIxed typings (function properties instead of methods in decorators)

- docs/intro/concepts.md
- docs/react/react-integration.md
- docs/react/react-performance.md
Hey,
I've updated the docs below. Feel free to merge at any point and I'll create a new PR for the remaining files.
-   [x] docs/intro/concepts.md
-   [x] docs/react/react-integration.md
-   [x] docs/react/react-performance.md
Only the great `docs/refguide` remains.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2452"><img src="https://gitpod.io/api/apps/github/pbs/github.com/zangornjak/mobx.git/0c641ee2daf5f84aa3245b1b2058b233380c9c0c.svg" /></a>
> Docs grammar corrections II

- docs/README.md
- docs/best/debugging-mobx.md
- docs/best/decorators.md
- docs/best/stateless-HMR.md
- docs/best/store.md
- docs/best/what-does-mobx-react-to.md
- docs/faq/migrate-to-6.md
- docs/intro/concepts.md
- docs/intro/installation.md
- docs/react/react-integration.md
- docs/react/react-performance.md
- docs/refguide/configure.md
- docs/refguide/extending.md
- docs/refguide/mobx-utils.md
- docs/refguide/modifiers.md
- docs/refguide/object-api.md
- docs/refguide/object.md
- docs/refguide/observable.md
- docs/refguide/observe.md
- docs/refguide/on-become-observed.md
Evening!
I've updated the docs below:
And some more, but those were mainly code comments that I skipped previously, and updates to already passed docs so they match the same overall style:
- warnings with icons and bold text (⚠️ **Warning**: ⚠️)
- check out instead of also see / see / see also
- uniform [🚀] instead of 🚀 in the contents, haven't touched the menus
- beginning of list (e.g. Tip:) and ending of heading
- etc.
**Q**: Can `docs/refguide/toJS.md` be removed in favor of `docs/refguide/api.md#tojs` since the former is never used in the docs, but the latter is once?
_Sorry about my estimation of completion time being off by a metric ton. I'll continue creating PRs until I reach the end (5 files remaining)._
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2460"><img …
> Docs grammar corrections III

- src/utils/utils.ts
Added support for plain objects from another window.
This should fix https://github.com/mobxjs/mobx/issues/2448
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2461"><img src="https://gitpod.io/api/apps/github/pbs/github.com/ConneXNL/mobx.git/a121f1cfa0cb0ab1701cf14c0ba280ab8fbc2206.svg" /></a>
> Added support for plain objects from another window

- CHANGELOG.md
Links were pointed to 404. 👀 
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2470"><img src="https://gitpod.io/api/apps/github/pbs/github.com/leader22/mobx.git/7ed9a5ad4635fb6d26c325caf8e057565c69027e.svg" /></a>
> Fix docs link in v6 CHANGELOG

- website/static/js/scripts.js
Fix bug introduced in https://github.com/mobxjs/mobx/pull/2502 and add one overlooked rocket emoji location
- `openTarget` should be executed after `addTooltipToRockets` to not break `openTargets`'s async scroll on refresh. Currently, the `details` element in `openTarget` is replaced by `addTooltipToRocket`'s innerHTML reassignment.
- add bottom prev/next doc page buttons to `addTooltipToRockets`
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2503"><img src="https://gitpod.io/api/apps/github/pbs/github.com/jheeffer/mobx.git/7edcf6fa2269f6db0218e3cfe2e30f2e4ed3b7b8.svg" /></a>
> Docs: fix broken openTarget and add prev/next button to tooltip

- docs/defining-data-stores.md
Hi there,
The new documentation is great! Here's a tiny improvement: `todo` cannot be const because it's reassigned two lines below if it doesn't exist.
This PR changes only documentation.
PS: When creating this PR, I see the old "MobX6 is WIP" PR template. You may want to update that template now.
> Fix example updateTodoFromServer

- docs/defining-data-stores.md
Change example code to run all calls to updateTodoFromServer (one per item in the result set) in a single transaction.
> docs: load all items in a single transaction

- docs/the-gist-of-mobx.md
Hello
While reading [The gist of MobX](https://mobx.js.org/the-gist-of-mobx.html#31-model-derived-values-using-computed), I found a small typo in the `TodoList` constructor. It does not have `this.todos` initialization. 
Meanwhile, [codesandbox](https://codesandbox.io/s/concepts-principles-il8lt?file=/src/index.js:718-737), which is provided at [the end of the documentation](https://mobx.js.org/the-gist-of-mobx.html#try-it-out), has initialization of `this.todos`
> docs: fix typo at TodoList constructor

- docs/react-integration.md
Just a few tiny documentation corrections.
> Fix <Observer> example in react-integration.md

- .changeset/tame-pens-bathe.md
- src/utils/global.ts
In a web-worker environment, there is no `global` or `window`, and therefore currently mobx explodes when running in a web-worker.
This PR replaces `window` with self, as in a browser environment `self === window`.
Please let me know if something additional is needed.
Thanks!
> support running in web-worker

- .changeset/pink-apricots-sparkle.md
- CHANGELOG.md
- src/api/makeObservable.ts
- test/v5/base/make-observable.ts
Fixes #2542
`options.deep` takes a precedence over `options.defaultDecorator`
> Fix #2542 makeAutoObservable not respecting deep option

- docs/defining-data-stores.md
In that context, method and function would be intended to express a method of a class.
I think it is better to use a same word 'method'.
> Modify to use a same word.

- docs/migrating-from-4-or-5.md
- Updating changelog url for migrating from 4 to 5
👋 Are you making a change to documentation only? Delete the rest of the template and go ahead.
> Updating changelog url for migrating from 4 to 5

- docs/installation.md
Docs fix:
In Mobx's [Installation document](https://mobx.js.org/installation.html), the link to download a js file from unpkg is broken. 
The link is currently heading to `mobx.umd.js` and needed to fix a correct path. But, I can't find a proper path of `mobx.umd.js` and changed to `mobx.umd.production.min.js` instead.
> Docs fix : fix a broken link to download js from unpkg cdn

- .changeset/olive-spies-cry.md
- packages/mobx/src/mobx.ts
-   [ ] **IMO unnecessary** - Added/updated unit tests 
-   [ ] **IMO unnecessary** - Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [X] Verified that there is no significant performance drop (`npm run perf`)
Fixes issue #2716
> Export `CreateObservableOptions` type

- .changeset/sweet-shrimps-float.md
- packages/mobx-react-lite/package.json
`sideEffects: false` is unsafe, because `mobx-react-lite/index.ts` contains a side effect https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/src/index.ts#L9. It was fixed in 2.2.2 https://github.com/mobxjs/mobx-react-lite/pull/314, but was reintroduced in some 3.x version.
> Remove sideEffects section in mobx-react-lite package.json

- .changeset/gorgeous-coats-rest.md
- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/src/undecorate.ts
If `keepDecorators` flag is passed to `mobx-undecorate` there is no need to create generic arguments for `makeObservable`.
> Do not create generic arguments if keepDecorators passed

- .changeset/calm-files-nail.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/action.ts
seanchas116 create this issue #2670, seanchas116 found mobx can't infer `action` callback arguments types correctly.
Previous pr #2213 #2217 (by @kubk ) fix it, but mobx6 remove it (I don't know why).
I recover it and add more unit test.
```js
// Promises
// TODO: re-enable
// Promise.resolve(1).then(
//     action(arg => {
//         assert<IsExact<typeof arg, number>>(true)
//     })
// )
```
I noticed this comment, so maybe we need check why this unit test be disabled previously.
@FredyC @urugator 
> If this pr isn't useful, just close it 😃
> Infer optional / promise action args type correctly

- .changeset/proud-tips-bathe.md
- packages/mobx/__tests__/v5/base/become-observed.ts
- packages/mobx/src/core/reaction.ts
> Fix 2686: onBecome(Un)Observed not firing for nested computeds

- .changeset/rude-berries-stare.md
- README.md
- docs/actions.md
- docs/observable-state.md
> Doc improvements

- .changeset/cuddly-pets-sort.md
- docs/configuration.md
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/api/configure.ts
- packages/mobx/src/core/globalstate.ts
- packages/mobx/src/types/actionannotation.ts
- packages/mobx/src/types/flowannotation.ts
- packages/mobx/src/types/observableobject.ts
Added new configuration option `safeDescriptors: boolean = true` as discussed in #2752
Improved configuration section in docs - should be now clearer what are the defaults.
> configure({ safeDescriptors: false })

- .changeset/shaggy-clocks-applaud.md
- packages/mobx/src/api/configure.ts
This is the follow-up to https://github.com/mobxjs/mobx/pull/2761 🙂 It was missed in the original PR. /cc @urugator 
> Add safeDescriptors to configure options type

- .changeset/witty-hotels-ring.md
- packages/mobx-undecorate/src/undecorate.ts
fix #2747 
`warn` util function's params `node`'s loc is null in some scenarios.
```ts
const line = lines[node.loc!.start.line - 1]  👈   //  when `loc` is null, codemod script crash
```
mobx-undecorate build on top of `jscodeshift` and use `@babel/parser` as ast parser
```js
const babylon = require("@babel/parser")
```
`jscodeshift` based on `recast`, `recast` inner logic will make loc be null in some scenarios.
https://github.com/benjamn/recast/blob/master/lib/util.ts#L180-L183
```js
} else if (node.declaration && isExportDeclaration(node)) {
// Nullify .loc information for the child …
```
> fix: mobx-undecorate don't crash when node's loc is null

- .changeset/great-pants-do.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/types/actionannotation.ts
- packages/mobx/src/types/flowannotation.ts
Non-writable actions and flows defined on prototype prevented initializing the prop via assigment inside constructor.
Since this PR, things defined on prototype won't use safe descriptors.
This doesn't mean that we support runtime prototype modifications, but we assume that doing so isn't common enough to justify this safety measure, while preventing other potentially valid usages.
> Fix: Inherited annotated fields are not assignable

- .changeset/two-rings-lay.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/api/iscomputed.ts
- packages/mobx/src/api/makeObservable.ts
- packages/mobx/src/types/observableobject.ts
- packages/mobx/src/types/type-utils.ts
Annotation cache was using `for in`, not picking up symbols. Object replaced with `Map` to avoid `ownKeys`.
Additionally `getAtom` and `isComputedProp` now accepts Symbols
> Fix makeAutoObservable + symbolic keys

- .changeset/few-hotels-clean.md
- packages/mobx/src/api/annotation.ts
- packages/mobx/src/api/decorators.ts
- packages/mobx/src/types/actionannotation.ts
- packages/mobx/src/types/computedannotation.ts
- packages/mobx/src/types/flowannotation.ts
- packages/mobx/src/types/observableannotation.ts
- packages/mobx/src/types/observableobject.ts
Avoids an annotation object copy per decorator application.
Since mixing decorators/annotations is not officialy supported (it may actually work, but there are not tests for it), annotation itself doesn't have to know that it's decorator - ~~once target has `storedAnnotationsSymbol` - meaning at least one decorator was applied - we assume that all annotations are decorators.
If one would try to mix decorators/annotation (unsupported), this change breaks check for non-existing prop (it won't throw).
The decorator detection could be made a bit more realiable by changing `make_` to accept additional `isDecorator` param and calling: `adm.make_(key, annotations![key], !annotations)` from `makeObservable`. 
Not sure if worth it ATM, but at least good to have this noted here.~~
EDIT: Changed to …
> Small decorators optimization

- .changeset/shy-mangos-shake.md
- packages/mobx/src/utils/global.ts
`globalThis` is a __standard__ global right now
should use it whenever available
The current code fails in sandbox environments where only standard `globaThis` exists (regression from 5.x which works fine)
> detect globalThis

- website/siteConfig.js
click it ->
jump to 404 ->
```diff
-   editUrl: "https://github.com/mobxjs/mobx/edit/mobx6/docs/",
+   editUrl: "https://github.com/mobxjs/mobx/edit/main/docs/",
```
> fix the mobx doc edit button jump link

- .changeset/wet-clocks-carry.md
- packages/mobx/src/mobx.ts
> ts: export IComputedFactory typescript type definition

- .changeset/quick-parrots-wink.md
- packages/mobx-undecorate/cli.js
This PR modifies mobx undecorate to spawn jscodeshift using the system path -child_process.spawn("jscodeshift", ...) instead of a relative path. The reasoning is that you should be able to reliably call a package by name if it is using a bin field in its package.json (as all node cli applications do) per the npm docs  https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin .
I also added an additional help message to the cli if users pass a --help arg. jscodeshift usage will be appended to the mobx-undecorate message
further only partially relevant info:
CJS require.resolve algorithm psuedo code: https://nodejs.org/api/modules.html#modules_all_together
ESM resolve algorithm https://nodejs.org/api/esm.html#esm_resolver_algorithm (likely 0 importance) …
> Mobx decorate 1.0.8

- docs/reactions.md
The docs are imo not clear enough on when the effect function of a reaction triggers. 
It's only after I read the notes on the `equals` option that I got  to know that there is an 'extra' check (it being the result of the data function) that determines if an effect is triggered.  I thought after reading the docs that the effect function would always be triggered if any of the dependencies change.
This makes it very easy to create all sorts of bugs if used incorrectly:
https://codesandbox.io/s/mobx-reaction-bug-tyssu?file=/src/index.ts
I added a "By default, the result of the _data_ function has to change in order for the _effect_ function to be triggered." in order to make the behavior more clear.
> Clarify when reactions effect functions trigger.

- .changeset/fluffy-coats-fry.md
- packages/mobx/__tests__/v5/base/tojs.js
- packages/mobx/src/api/tojs.ts
Fixes: #2871 in BC manner.
We may want to reconsider which kind fo keys `toJS` returns.
> Fix #2871 toJS throws with configure({ useProxies: "ifavailable" })

- .changeset/rich-buttons-call.md
- packages/mobx-react/__tests__/inject.test.tsx
- packages/mobx-react/src/utils/utils.ts
I think it's best to use `hoist-non-react-statics` https://github.com/mridgway/hoist-non-react-statics, but it was intentionally removed some time ago.
Fixes: #2829.
> inject shouldn't change original displayName of component that uses forwardRef

- .changeset/reduce-useObserver-gc-pressure.md
- packages/mobx-react-lite/src/useObserver.ts
Tiny performance improvement,  create ObjectToBeRetainedByReact once per component instance and not every component render
> [Perf] Reduce useObserver gc pressure

- .changeset/witty-bananas-care.md
- packages/mobx/src/mobx.ts
I find that "Symbol" is duplicated and should be removed
> Remove duplicate global property check

- .changeset/plenty-rice-love.md
- packages/mobx-react-lite/src/useObserver.ts
- packages/mobx-react-lite/src/utils/utils.ts
1. **removed `useForceUpdate` abstraction**
It was used on single place and impl is trivial.
2. **removed `useCallback`**
`forceUpdate` isn't passed anywhere where it could break memoization, therefore no need for `useCallback`.
The closure is recreated every render one way or another.
3. **Replace increment with unique reference, see #2982.** 
The choice to use `[]` is arbitrary. Feel free to change to whatever performs better.
> forceUpdate fix and refactor, alternative to #2982

- .changeset/wise-seals-kick.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/autorun.ts
This PR gives the `opts.equals` proper typing so that TypeScript knows that the `equals` function passed to it is comparing values of the return type of `expression` rather than `any`.
> Give proper typing to opts.equals of reaction

- docs/installation.md
- website/i18n/en.json
- website/siteConfig.js
https://babeljs.io/docs/en/assumptions
> Since Babel 7.13.0, you can specify an assumptions option in your configuration to tell Babel which assumptions it can make about your code, to better optimize the compilation result. Note: this replaces the various loose options in plugins in favor of top-level options that can apply to multiple plugins (RFC link).
> doc: babel assumptions

- .changeset/loud-rules-count.md
- packages/mobx-react/__tests__/issue806.test.tsx
- packages/mobx/__tests__/v5/base/trace.ts
- packages/mobx/__tests__/v5/base/typescript-decorators.ts
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/core/computedvalue.ts
- packages/mobx/src/core/derivation.ts
`trace` logs when computed becomes suspended as discussed in:
https://github.com/mobxjs/mobx/issues/2859#issuecomment-831184535
`requiresObserver` no longer throws, but warns, so it's consistent with `computedRequiresReaction`, `observableRequiresReaction`, etc
Improved console messages.
> trace(): log when computed becomes suspended

- docs/react-integration.md
Fix a typo in the example demonstrating dereferencing before `observable` is called.
> docs: Update react-integration.md

- packages/mobx-react-lite/package.json
- packages/mobx-react/package.json
Keep all subpackage homepage is same as mobx: `https://mobx.js.org/`
> chore: keep homepage identically

- docs/actions.md
- docs/api.md
Closer description of actual implementation.
> doc: Improve description of `action` and `transaction` (#3017)

- .changeset/many-moons-turn.md
- packages/mobx/src/api/when.ts
Currently, the `WHEN_TIMEOUT` error is thrown from a `setTimeout`, which usually contains no stack itself, this makes it impossible to distinguish between different places throwing it, and hard to track where it is from, and thus make it a high-frequency error in our logging which is basically not actionable.
This PR creates the error earlier when the `when` starts, so that it preserves the stack on where the `when` is called.
Unconditionally creating an error might slightly regress the performance of `when`, but it only happens when `timeout` is specified. And `when` itself is probably not all that performance-critical anyway I suppose.
-   [ ] Verified that there is no …
> Create WHEN_TIMEOUT error earlier to capture useful stack

- docs/actions.md
Developers should avoid using `event.stopPropagation()`
See https://css-tricks.com/dangers-stopping-event-propagation/ for the dangers
> refactor(docs): replace event stop propagation with prevent default in actions page

- .changeset/dirty-ears-push.md
- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/src/undecorate.ts
Hi!
This PR is doing the following changes to `mobx/undecorate` codemod: 
- Add support for modules with default export on the same line as the class declaration.
Currently the codemod produce a broken output if you use default exports for your classes in the following way:
```js
import {observer, inject} from 'mobx-react'
@inject('test')
@observer
export default class X extends React.Component {}
```
- HoC are now separately wrapping the class at the export level, instead of at the declaration level. This fixes a bug where linting was broken after using the codemod if codebase was using `eslint-plugin-react`, because the [prop-types plugin](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) could not anymore work (due to the HoC wrapping the entire …
> fix(undecorate): add support for default export classes + fix eslint-plugin-react compat

- docs/subclassing.md
Problem Statement: 
When reading the docs for `subclassing` they reference, both in text as well as code implementation, a method `override`. 
However, from the readers point of view it's never shown where this method comes from.
Expected Behavior:
Reading the code snippet should show the usage pattern for `override` in it's entirety, including importing it.
Actual Behavior:
The code snippet uses a non implemented method `override`.
Updated Behavior:
The code snippet now imports the `override` method which resolves the missing implementation detail.
> docs update: subclassing missing override import

- .changeset/moody-kids-punch.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/intercept.ts
- packages/mobx/src/api/observe.ts
Fixes: https://github.com/mobxjs/mobx/issues/3179
Both Map & Set resulted in wrong type inference. Now the correct type inference is covered with tests.
> Fix type inference of observe function (Close #3179)

- .changeset/beige-goats-vanish.md
- packages/mobx/src/core/atom.ts
This is more like [the docs](https://mobx.js.org/custom-observables.html#atoms)
Reason for creating this PR:
> Make `IAtom['reportObserved']` return `boolean`

- .changeset/ninety-rings-move.md
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/types/observablearray.ts
Hello! I noticed an error in my application when working with long lists, traced it back down to here.
Here's a minimal repro (included in the new test case) https://codesandbox.io/s/inspiring-matsumoto-kbjzc?file=/src/index.ts
It only seems to happen when both arrays are larger than `MAX_SPLICE_SIZE` and the original array is larger than its replacement
Cheers!
> Fix: RangeError in ObservableArray.replace for large arrays

- docs/understanding-reactivity.md
In the example above, the instance name is `message` without `s`
> Doc: Correct the instance name

- .changeset/curly-vans-enjoy.md
- docs/configuration.md
- packages/eslint-plugin-mobx/README.md
- packages/eslint-plugin-mobx/__tests__/TODO-missing-observer.js
- packages/eslint-plugin-mobx/__tests__/TODO-no-anonymous-observer.js
- packages/eslint-plugin-mobx/package.json
- packages/eslint-plugin-mobx/preview/.eslintrc.js
- packages/eslint-plugin-mobx/preview/make-observable.js
- packages/eslint-plugin-mobx/preview/missing-observer.js
- packages/eslint-plugin-mobx/preview/no-anonymous-observer.js
- packages/eslint-plugin-mobx/src/index.js
- packages/eslint-plugin-mobx/src/missing-observer.js
- packages/eslint-plugin-mobx/src/no-anonymous-observer.js
- packages/mobx-react-lite/__tests__/observer.test.tsx
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/package.json
- packages/mobx-react/src/observerClass.ts
- packages/mobx/__tests__/v5/base/decorate.js
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/when.ts
- packages/mobx/src/types/dynamicobject.ts
- packages/mobx/src/types/observablemap.ts
- packages/mobx/src/types/observableobject.ts
- packages/mobx/src/utils/utils.ts
- yarn.lock
See [README.md](https://github.com/mobxjs/mobx/pull/3219/files#diff-f7dad23cf5aef1d36e8bc064e49615120f537edb709fc91312b5a68440856f6c)
> eslint: missing-observer, no-anonymous-observer

- .changeset/real-kangaroos-type.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/utils/utils.ts
Fixes #3197
`isPlainObject` compares stringified proto constructor with `Object` constructor, however we did not make sure that the `constructor` is actually own property of the prototype. Therefore in cases where constructor was not defined, like `Object.create({})`, we were comparing constructor inherited from `Object`, leading to false positive.
lodash impl for reference:
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L12036
> Fix `isPlainObject` (#3197)

- .changeset/moody-rabbits-roll.md
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/core/computedvalue.ts
This allows to opt-out of global configuration per computed basis. Previously it was only possible to opt-in.
See: https://github.com/mobxjs/mobx/discussions/3213
> `requiresReaction` always takes precedence over global `computedRequiresReaction`

- .changeset/late-elephants-remain.md
- packages/mobx/src/utils/eq.ts
> fix: `isFunction`shouldn't be used

- .changeset/warm-foxes-hang.md
- packages/mobx-react-lite/__tests__/observer.test.tsx
- packages/mobx-react-lite/src/observer.ts
- packages/mobx-react/__tests__/observer.test.tsx
- yarn.lock
partial fix for #2721 
For whatever reason, in react 17, `getComponentName` returns the name of the memoized component, rather than the name of the wrapper itself:
https://github.com/facebook/react/blob/12adaffef7105e2714f82651ea51936c563fe15c/packages/shared/getComponentName.js#L88
So how does `displayName` work on memoized component? Memoized component defines `displayName` as a getter/setter pair, where setter in addition to setting "own" name for the wrapper, [also modifies the name of the original component](https://github.com/facebook/react/blob/12adaffef7105e2714f82651ea51936c563fe15c/packages/react/src/ReactMemo.js#L41):
```javascript
const Original = function() {};
const Memoized = memo(Original);
Memoized.displayName = 'memoized';
console.log(Original.displayName === …
```
> Support `displayName` on anonymous components

- docs/understanding-reactivity.md
_"reading"_ is dereferencing an object's property, which can be done through destructuring (eg. `const {name} = user`)
> docs: add about destructuring

- .changeset/thin-adults-leave.md
- packages/mobx/src/api/tojs.ts
Warn in `toJS` docs about deep cloning partial observables, to avoid issues with some properties being deep clones while others are not. 
I have faced this issue while upgrading to MobX 6 and I believe it will save other people some headaches if it is clear that `toJS` has this limitation.
Relates to https://github.com/mobxjs/mobx/issues/2912
> Warn in `toJS` docs about deep cloning partial observables

- .changeset/smooth-penguins-pretend.md
- packages/mobx/src/types/legacyobservablearray.ts
- packages/mobx/src/types/observablemap.ts
- packages/mobx/src/utils/utils.ts
Related issue: #3286
Not needed
These changes are TS-only, they don't affect runtime performance 
- Removed any from ObservableMap public API
- Added explicit `any` to assertion functions
- Removed obsolete `ts-ignore`
- All the codestyle changes were made by the pre-commit hook
> Remove any from ObservableMap public API (Close #3286)

- .changeset/clever-gorillas-warn.md
- .changeset/soft-jeans-stare.md
- packages/mobx-react-lite/__tests__/observer.test.tsx
- packages/mobx-react-lite/src/observer.ts
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/observer.tsx
Solves #2527, #3267
Added support for `observable(forwardRef(fn))`
Deprecated  `observable(fn, { forwardRef: true })` - prints warning on devel.
`observer(memo(fn))` now throws (previously only `mobx-react`'s `observer` was throwing)
`observer(forwardRef(fn))` delegates to `mobx-react-lite`, it no longer generates extra `<Observer>` element and it applies `memo` correctly (previously these were not memoized)
I would appreciate if someone could check if typing is correct.
> #2527 Consolidate behavior of React.forwardRef & observer

- docs/installation.md
We ran into a problem while installing mobx. We copied and used the original snippet and it broke our app (couldn't log or get hot-reload on react native). We got a warning about the 'loose': false but following this documentation didn't get us to where we needed to be.
I believe this is a clearer and more complete explanation of what is actually needed for configuration.
> Clear up documentation

- .changeset/chilled-cups-raise.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/intercept.ts
- packages/mobx/src/api/observe.ts
fixes #3303
Probably just overlooked in: #3180
> Fix #3303 missing type inferrence of `observe` and `intercept` for arrays

- .changeset/stale-melons-approve.md
- docs/reactions.md
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/core/derivation.ts
- packages/mobx/src/core/reaction.ts
> Fix #3315: `requiresObservable` always takes precedence over global `reactionRequiresObservable`

- docs/computeds.md
If a computed value depends on a value that is not observable, the cache will not be invalidated when that value changes.
For example:
```javascript
window.x = true;
class MyState {
a = "a";
b = "b";
constructor() {
makeAutoObservable(this);
}
get foo() {
if (window.x)
return this.a;
else
return this.b;
}
}
```
In this code, only `a` is registered as a dependency of the computed value `foo`, even though `foo` also depends on `x` and `b`.
(And oh boy, I learned that the hard way...)
> Documentation: Add rule for Computed Values

- .changeset/fluffy-crabs-exercise.md
- .changeset/tall-seas-study.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/types/observableset.ts
Related issue: https://github.com/mobxjs/mobx/issues/3337
> Replace 'any' with a generic in Set (Close #3337)

- packages/mobx-react-lite/src/observer.ts
Corrected the spelling of `deprecated`
> Fix deprecated spelling in console.warn

- README.md
Individual backers link on https://mobx.js.org/README.html leads to a Not Found message due to relative pathing.
This will point to the file on GitHub which is what a user is taken to when clicking the link on https://github.com/mobxjs/mobx.
> Fix individual backers link in main readme

- .changeset/brown-camels-smash.md
- packages/mobx-react-lite/src/observer.ts
- packages/mobx-react/src/inject.ts
- packages/mobx-react/src/observerClass.ts
> Alternative PR for #2741
When I try to solve this problem #2721 , I noticed that mobx-react(and lite) source code use 
deprecated react type definition, Such as `RefForwardingComponent ` `React.Props`
and `StatelessComponent `, so I created a PR to replace these with official recommended type def.
```ts
/**
* @deprecated Use ForwardRefRenderFunction. forwardRef doesn't accept a
*             "real" component.
*/
interface RefForwardingComponent <T, P = {}> extends ForwardRefRenderFunction<T, P> {}
```
```ts
/**
* @deprecated. This was used to allow clients to pass `ref` and `key`
* to …
```
> chore: replace the deprecated react type definition

- .changeset/fifty-llamas-fail.md
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/observerClass.ts
- packages/mobx/src/mobx.ts
Bugfix [#3392](https://github.com/mobxjs/mobx/issues/3392)
>  Bugfix #3392

- .changeset/clean-islands-retire.md
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/observerClass.ts
> Fix #3395: observer not working with <React.StrictMode>

- docs/react-integration.md
Almost 1 year ago I had to find a logger for Mobx. I stumbled upon `mobx-logger`, tried it, but unfortunately its output was limited with Mobx 6. I created an issue: https://github.com/winterbe/mobx-logger/issues/34
The issue has no response since then. Last publish of the package was 4 years ago: https://www.npmjs.com/package/mobx-logger
It looks like the package isn't maintained anymore. I've created `mobx-log` to have a Mobx 6 compatible logger. This packages is new and less popular (25 stars VS 230 stars, [503](https://www.npmjs.com/package/mobx-log) weekly downloads vs [3997](https://www.npmjs.com/package/mobx-logger)), but it includes more:
- Chrome formatters for ES6 Proxy
- Access to stores via browser console 
- The issues are being addressed (so far 😅) [Example …
> Suggest mobx-log instead of mobx-logger

- .changeset/clean-boats-repeat.md
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/types/observablemap.ts
This is really helpful after #3287 since that PR made it so that this use case failed to type check.
I added a test to make sure that this doesn't regress.
> Allow using 'as const' for creating tuples for map.replace

- .changeset/red-cups-yell.md
- README.md
- docs/README.md
- docs/actions.md
- docs/api.md
- docs/custom-observables.md
- docs/enabling-decorators.md
- docs/migrating-from-4-or-5.md
- docs/observable-state.md
- docs/subclassing.md
- packages/mobx-react/__tests__/Provider.test.tsx
- packages/mobx-react/__tests__/__snapshots__/observer.test.tsx.snap
- packages/mobx-react/__tests__/disposeOnUnmount.test.tsx
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/observerClass.ts
- packages/mobx/CHANGELOG.md
- packages/mobx/src/api/decorators.ts
- packages/mobx/src/types/observableobject.ts
- website/i18n/en.json
- website/sidebars.json
- website/static/css/custom.css
Hi. This pull request changes a handful of things which I found to be confusing when reading this otherwise excellent documentation. I apologize if this PR is too bold — do of course feel free to close this PR should you disagree with these changes.
The changes are:
* I found the lack of a link to the API in the sidebar to be extremely confusing. It turns out that it was in the header, but it still always takes me a while to remember where to look for it.
* The API docs include links to more detailed articles on some topics, but that link is "hidden" behind the "Usage:" label. I did not figure that out at first, and so I've changed the link to a "(further information)" label.
* In "Creating custom observables", it was not clear that "the concept of atoms" refers to a class used interally …
> Documentation: A slight revamp of the README, wording, and clearer links

- README.md
- packages/mobx-react-lite/README.md
- packages/mobx-react/README.md
The PR brings coveralls.io badges back. I've also removed Typescript/Prettier badges because nowadays these tools are de facto standard. Let's avoid excess information to not overwhelm reader.
Regarding allowing coveralls job to fail on CI, there is no clean solution yet, the issue is still open: https://github.com/actions/toolkit/issues/399
For example, one of the workarounds https://github.com/actions/toolkit/issues/399#issuecomment-607465968 would allow to merge a PR with optional failed job, but GitHub will show the whole PR as failed (with ❌ symbol). 
@urugator How often do you encounter coveralls random fails?
Here coveralls job failed because the tests failed too: https://github.com/mobxjs/mobx/pull/3458/commits/be29cd01257004c4433414ea4d3101d459ef95c8
> Coveralls badges

- .github/ISSUE_TEMPLATE/bug.md
The PR adds React Native codesandbox link to the issue template. This codesandbox has a web preview, so it's much more easier to check than installing React Native with a bunch of related tools like emulator locally. For example here https://github.com/mobxjs/mobx/discussions/3480 the provided codesandbox helped to narrow down the issue.
> Add React Native codesandbox to the issue template

- .changeset/fresh-suns-listen.md
- packages/mobx/src/types/legacyobservablearray.ts
Reintroduced workaround from mobx < 6.
Did not test as I don't have a means to do so. 
Fixes #3514
> Fix 3514: legacy array compat with Safari 9

- docs/collection-utilities.md
Missing import for `autorun` in the example on https://mobx.js.org/collection-utilities.html
> docs(collection-utilities): Add missing import

- .changeset/popular-comics-tap.md
- docs/reactions.md
- package.json
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/when.ts
- yarn.lock
Initially I tried adding it to the `_when` function to support the callback-based `when()`, but I wasn't sure how to properly clean up the event listener in the disposer so I went for this approach instead.
Also not sure why it requires @types/node 18, according to node docs AbortSignal was added in node 15 / 14.18.
> feature: abort when() using AbortSignal

- website/static/getting-started.html
Documentation change only.
When including the webfont from Google Fonts, only regular roman was added, and italics/bolds are fallbacking to unexpected styles. This change updates the webfont url to include roman, italics, roman bold and italics bold.
Before:
After:
> Add missing webfont weight and style for getting started page

- .changeset/lemon-moles-clap.md
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/core/observable.ts
> Make return value of reportObserved match invoke of onBecomeObserved

- .changeset/polite-meals-drop.md
- packages/mobx-react/__tests__/context.test.tsx
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/inject.ts
Resolves: https://github.com/mobxjs/mobx/issues/3532
As @DanielSWolf wrote (thanks for that!): "This error occurs because TypeScript 4.8 is stricter than previous versions regarding unconstrained type parameters (see the [blog entry announcing TypeScript 4.8](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to))." 
I confirm that adding constraint to the generic fixes the issue. Now the generic constraints are identical to `IStoresToProps`: https://github.com/mobxjs/mobx/blob/a39ce7fbe19f92348470ef71ad60555c37a5d5e9/packages/mobx-react/src/types/IStoresToProps.ts#L2+L6
I've chosen `minor` instead of `patch` because it's kinda BC break but at the same time it's a bugfix.
> Make mobx-react compatible with TS 4.8+

- packages/mobx-react/README.md
Related discussion: https://github.com/mobxjs/mobx/discussions/3602
I've searched for all the mentions of `https://mobx-react.js.org` in the codebase.
> Remove old documentation mentions

- .changeset/angry-ghosts-obey.md
- package.json
- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/package.json
- packages/mobx-undecorate/src/undecorate.ts
- yarn.lock
https://github.com/mobxjs/mobx/discussions/3615
`yarn upgrade` throws 
`error An unexpected error occurred: "expected workspace package to exist for \"jsonfile\"".`
~~So the only way to upgrade deps for me is to delete `yarn.lock` and `yarn install`. Therefore the `yarn.lock` changes.~~
Solved by removing and reintroducing jscodeshift dep.
> [undecorate] fix: non-null assertion operator is removed

- .github/ISSUE_TEMPLATE/bug.md
The dependencies has been updated. Also the current link is now saved under my profile so we won't need to update the link in bug.md when the playground needs an update next time.
> Update link to expo playground in bug.md

- .changeset/weak-oranges-promise.md
- packages/mobx-react-lite/__tests__/api.test.ts
- packages/mobx-react-lite/src/index.ts
> fix #3650 regression clearTimers -> clearTimes

- .changeset/thin-bugs-boil.md
- packages/mobx-react-lite/package.json
Running prepublish locally on an empty check-out fails the mobx-react-lite build, as the types are nog generated when mobx itself hasn't been build:
```
(typescript) Error: /Users/mweststrate/Desktop/mobx/packages/mobx-react-lite/src/useLocalStore.ts(1,28): semantic error TS2307: Cannot find module 'mobx' or its corresponding type declarations.
Error: /Users/mweststrate/Desktop/mobx/packages/mobx-react-lite/src/useLocalStore.ts(1,28): semantic error TS2307: Cannot find module 'mobx' or its corresponding type declarations.
```
Fixed it by forcing a MobX build in the prepublish script
> fix: fix mobx-react-lite release issue, fixes #3662

- .changeset/fifty-rivers-doubt.md
- packages/mobx/src/api/trace.ts
This PR disables the `trace` functionality in the production build instead of throwing an error. Related discussion: https://github.com/mobxjs/mobx/discussions/3708
> Make trace() noop in production build

- .changeset/seven-poems-sneeze.md
- .changeset/spotty-emus-hear.md
- packages/mobx-react-lite/__tests__/observer.test.tsx
- packages/mobx-react-lite/__tests__/strictAndConcurrentModeUsingFinalizationRegistry.test.tsx
- packages/mobx-react-lite/__tests__/useAsObservableSource.deprecated.test.tsx
- packages/mobx-react-lite/__tests__/useAsObservableSource.test.tsx
- packages/mobx-react-lite/__tests__/useLocalObservable.test.tsx
- packages/mobx-react-lite/__tests__/useLocalStore.deprecated.test.tsx
- packages/mobx-react-lite/src/useObserver.ts
- packages/mobx-react/__tests__/finalizationRegistry.tsx
- packages/mobx-react/__tests__/hooks.test.tsx
- packages/mobx/__tests__/v5/base/extendObservable.js
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/extendobservable.ts
- packages/mobx/src/api/makeObservable.ts
- packages/mobx/src/api/observable.ts
- packages/mobx/src/core/atom.ts
- packages/mobx/src/core/globalstate.ts
- packages/mobx/src/core/observable.ts
- packages/mobx/src/types/legacyobservablearray.ts
- packages/mobx/src/types/observablearray.ts
- packages/mobx/src/types/observablemap.ts
- packages/mobx/src/types/observableobject.ts
- packages/mobx/src/types/observableset.ts
- packages/mobx/src/types/type-utils.ts
-   fix: #3728: Observable initialization updates state version.
-   fix: Observable set initialization violates `enforceActions: "always"`.
-   fix: Changing keys of observable object does not respect `enforceActions`.
-   fix: #3734: `isolateGlobalState: true` makes observer stop to react to store changes
> Fix #3728: observables initialization should not update state version

- .changeset/light-birds-grow.md
- packages/mobx-react-lite/src/useObserver.ts
This diff disables the usage of global state versioning. The reasoning here is:
* global state versioning is principle more correct
* effectively it doesn't make the implementation more compatible with concurrent mode, both implementations fail layer 3 compatibility
* in neither cases, the snapshot represents what actually will be read during render; as the latest version of all data is read, instead of the state described by the snapshot version. 
* since the local versioning approach doesn't break #3728 (for which could be argued it is unidiomatic), there seems at this moment little upside to the global version approach.
This PR deliberately doesn't clean up the underlying infra; the tracking of a global state version in the first place. I will probably put up a separate PR for that, …
> Fix: disable global state version usage in observer. Fixes #3728

- docs/defining-data-stores.md
`makeAutoObservable` ignores instances of classes from autoconversion, so it's not necessary to exclude it. Helps to avoid confusion: https://github.com/mobxjs/mobx/discussions/2847#discussioncomment-7314913
> Remove { rootStore: false } from docs since it's not needed

- .changeset/hip-bulldogs-act.md
- packages/mobx-react/src/observerClass.ts
After upgrading from MobX 4 to MobX 6 in a React Native project (React 18.2, no StrictMode), I noticed almost all of my screens went stale shortly after rendering.
An observer class component is registered with `observerFinalizationRegistry` like so:
```ts
_observerFinalizationRegistry.register(this, admin, this);
```
The third argument is the `token`, which is used to store the registration in a Map. In `componentDidMount` the finalization is then unregistered so it is allowed to stay alive, but using `admin` as the token, not `this`:
```ts
_observerFinalizationRegistry.unregister(admin);
```
`admin` is not registered to begin with, so the finalization does not get cleaned up, resulting in every class component going stale after about 10 seconds of being rendered.
-   [ ] Added/updated …
> Fix: observer class components going stale after 10 seconds

- packages/mobx-react/__tests__/finalizationRegistry.tsx
Just addressing todo item that was pending the merge of https://github.com/mobxjs/mobx/pull/3620
> chore(types): Remove unnecessary declaration of weakRef

- .changeset/light-birds-grow.md
- packages/mobx-react-lite/src/useObserver.ts
- packages/mobx/__tests__/v5/base/observables.js
- packages/mobx/src/core/atom.ts
- packages/mobx/src/core/globalstate.ts
- packages/mobx/src/core/observable.ts
Follow up of #3763, cleanup global stateVersion. Kept initObservable as is, as it handles several flags around warnings etc better.
> State version cleanup

- .changeset/sweet-experts-allow.md
- packages/mobx/__tests__/v5/base/action.js
- packages/mobx/src/core/action.ts
-   [x] ~~Updated `/docs`. For new functionality, at least `API.md` should be updated~~
Fixes #3653 in that it transparently forwards the output of `toString` for functions wrapped in an action
> fix: action transparently forwards toString of underlying function

- .changeset/six-pugs-impress.md
- packages/mobx/src/api/autorun.ts
HI Folks
This PR is about `reaction` and memory retainment preventing object beeing garbage collected
For some reason, the `reactionRunner` of a reaction creates a closure around an `oldValue` and so the reference to the `oldValue` is kept untill a newValue is computed.
I can see no reason for keeping such a reference "alive", `oldValue` could just be declared in the scope of the `reactionRunner` as it is the only place where it is used. Doing so, the `oldValue` can be garbage collected if needed.
No additional Unit test is needed for such a change, and there is no backward compatibility issue as it only touches internal/private stuff within a `reaction`.
> Prevent Reaction From Keeping a Reference to The OldValue

- docs/installation.md
The link to decorators in the [installation](https://mobx.js.org/installation.html) documentation is incorrect. It generates the link as `https://mobx.js.org/enabling-decorators.md` instead of `https://mobx.js.org/enabling-decorators.html`. This PR fixes it.
Note: I've tested this locally, seems to be working fine.
> fix: Update the links to enabling-decorators

- .changeset/thirty-beans-dress.md
- packages/mobx-react-lite/src/useObserver.ts
Fixes #3826
Fixes double rendering of component due to difference of snapshot values in `getSnapshot()` and `getServerSnapshot()` on initial rendering.
> fix(mobx-react-lite): fix double component rendering due to empty getServerSnapshot

- .changeset/wicked-cheetahs-build.md
- packages/mobx-react-lite/src/observer.ts
this patch addresses issue with environments where function name property is not configurable, notably pre-ES2015.
the same condition exists in MobX: [core/action.ts](https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/core/action.ts#L54).
regarding tests, I couldn't find a feasible way to seal a function, which was also discussed in #2262.
<details>
```shell
$ podman run --rm node:0.12 node -p 'Object.getOwnPropertyDescriptor(function() {}, "name")'
{ value: '',
writable: false,
enumerable: false,
configurable: false }
$ podman run --rm node:0.12 node -e 'Object.defineProperty(function() {}, "name", { value: "foobar" })'
[eval]:1
Object.defineProperty(function() {}, "name", { value: "foobar" })
^
TypeError: Cannot redefine property: name
at Function.defineProperty (native)
at …
```
> fix: ensure observer component name is only set when configurable

- .changeset/swift-numbers-prove.md
- packages/mobx/src/core/derivation.ts
TL;DR Preallocating a `size + 100` item array when tracking dependencies seems overly generous and can lead to more frequent garbage collections, causing jank. This PR replaces that with relative legroom (we preallocate 120% of space used by dependencies in the last run).
Let's consider this scenario where we read 1M computed values in an `autorun`.
```javascript
const obs = mobx.observable.box(1);
const arr = Array.from({length: 1_000_000}, () => mobx.computed(() => obs.get()));
mobx.autorun(() => {
arr.forEach((val) => val.get());
});
function main() {
// Recompute computeds in autorun.
mobx.runInAction(() => obs.set(obs.get() + 1));
}
window.__main = () => main();
```
A million may seem like a lot but if we read e.g. 2000 computed values in every frame of an interaction and the …
> Reduce memory overhead of tracking

- packages/mobx/src/api/autorun.ts
- packages/mobx/src/types/legacyobservablearray.ts
- packages/mobx/src/types/observablearray.ts
> fix: typos

- .changeset/short-hats-move.md
- packages/mobx-react-lite/src/useAsObservableSource.ts
There is a TypeScript issue https://github.com/microsoft/TypeScript/issues/43541 that is affecting `mobx-react-lite` package. This gives some warnings/errors when using `mobx-react-lite` with Rollup:
```
node_modules/mobx-react-lite/es/useAsObservableSource.js (1:13) Error: The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten1: var __read = (this && this.__read) || function (o, n) {
^
2:     var m = typeof Symbol === "function" && o[Symbol.iterator];
3:     if (!m) return o;
```
Even though this file/function is not used anywhere in the app it is still included in index.js file and hence parsed by rollup.
In order to work this around I changed the code structure a bit, looks not that great, but this way the output is not polluted. I am …
> [mobx-react-lite] Workaround for typescript issue #43541

- .changeset/seven-rules-add.md
- packages/mobx/src/core/reaction.ts
- packages/mobx/src/types/observableobject.ts
This is typing only PR.
Current interface definition for `IReactionDisposer` is
```
export interface IReactionDisposer {
(): void
$mobx: Reaction
}
```
but that's wrong because because like so typescript considers the property key `$mobx` to be a string, whereas it is a symbol. The correct indexing type is given by 
```
export interface IReactionDisposer {
(): void
[$mobx]: Reaction
}
```
[Edit] : same thing for `IIsObservableObject`
> Fix IReactionDisposer and IIsObservableObject  Typing

- .changeset/quiet-bottles-remember.md
- package.json
- yarn.lock
This hopefully fixes #3833 and other failing releases; as the prepublish scripts weren't running
> Fix release process

- docs/react-integration.md
Delete unnecessary `useState` from code example
> docs: remove unnecessary useState

- docs/installation.md
This adds a note for Next.js users, who (unintuitively) must configure babel (which is normally not needed at all) even if their project uses typescript. I think this is worth including because Next.js is relatively popular, and following the instructions as stated here simply doesn't work for unclear reasons. I spent the better part of an evening debugging this, only to eventually figure out that Next.js uses babel for compilation even if the project is set up with/written in typescript and doesn't have a babel config file yet.
Had I not had an evening free that I felt like spending on this, I probably would have given up entirely on MobX, as this was my first project to try it out and it seemed to just not work when used as directed (as all typescript-declared class fields without …
> Documentation: Add installation.md note about Next.js

- .changeset/lovely-lemons-joke.md
- packages/eslint-plugin-mobx/README.md
- packages/eslint-plugin-mobx/src/exhaustive-make-observable.js
Adds an option for the `mobx/exhaustive-make-observable` eslint rule to configure whether fields are annotated with `true` or `false` with the autofixer.
This option defaults to `true` if not present or an invalid value is received to maintain existing behavior.
-   [x] Added/updated unit tests -- No unit testing in the eslint package, but I have tested these changes against some other projects that use this rule.
Note: It looks like some formatting rules have changed since the last time this file was touched so there's quite a lot of changes.
Closes #3876
> feat(eslint-plugin-mobx): configurable default autofix annotation for makeObservable

- .changeset/dirty-turtles-marry.md
- packages/mobx/__tests__/v5/base/errorhandling.js
- packages/mobx/src/core/atom.ts
- packages/mobx/src/core/computedvalue.ts
- packages/mobx/src/core/observable.ts
-   [] N/A: Added/updated unit tests
-   [] N/A: Updated `/docs`. For new functionality, at least `API.md` should be updated
`ComputedValue` is currently 112 bytes in 64-bit chromium browsers, and it's not unreasonable to see 10s or 100s of thousands of these on very large apps. This makes this class IMO a reasonable target for memory optimization, given small changes can give big wins in absolute memory.
This change takes four boolean fields and stores them in one bitfield, adding getters and setters to keep the API to access them the same.
This shrinks 112 bytes down to 100 (verified in devtools) by removing 4x 4 byte booleans and replacing them with 1x 4 byte integer in v8. In Safari the bools …
> Shrink ComputedValue using a bitfield

- .changeset/fresh-apricots-heal.md
- packages/mobx/src/types/observablemap.ts
- packages/mobx/src/utils/utils.ts
Fixes #3892 
Do I have to add unit tests for this change? I'm not sure is it even possible to make cross-realm ES6 Map/Set instance in jest/jsdom test envionrment.
> Fix ES6 Map/Set checks for cross-window scripts

- .changeset/fifty-tools-reply.md
- package.json
- packages/eslint-plugin-mobx/preview/missing-observer.js
- packages/eslint-plugin-mobx/src/missing-observer.js
> Fix #3908: mobx/missing-observer rule false positive with forwardRef

- .changeset/soft-beans-dream.md
- docs/enabling-decorators.md
- packages/mobx/__tests__/decorators_20223/stage3-decorators.ts
- packages/mobx/src/types/actionannotation.ts
Similar to #3883 (credit to @Obi-Dann ) but add extra handling for `@action.bound` on field, for example 
```
class A {
@action.bound
doSomething = function() {...} // `this` should be bound to instance of class A
}
```
fix #3879
> fix: Allow action field decorators without makeObservable (#3879)

- packages/mobx-react-lite/src/observer.ts
Added some JSDoc that marks `IObserverOptions` as deprecated along with its individual properties. This gives some developers some feedback inside their editors instead of `console.warn` messages at runtime.
> deprecate `IObserverOptions` options and its properties in JSDoc

- .changeset/neat-ants-relate.md
- package.json
- packages/mobx/__tests__/v5/base/map.js
- packages/mobx/__tests__/v5/base/set.js
- packages/mobx/src/types/observablemap.ts
- packages/mobx/src/types/observableset.ts
- packages/mobx/src/utils/iterable.ts
- yarn.lock
Fixes https://github.com/mobxjs/mobx/issues/3927
TypeScript 5.6.x introduces new [Iterator Helper Methods](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#iterator-helper-methods) that enhance the `IterableObject` interface with methods like `map`, `flatMap`, `take`, and `drop`. However, when the `esnext` target is enabled, MobX becomes incompatible as its current implementation lacks these methods, resulting in type errors.
This PR addresses the compatibility issues by:
- **Updating the `IterableObject` Interface**: Aligning MobX’s implementation with …
> Fix Typescript 5.6.x support by introducing esnext iterator helpers (#3927)

- docs/actions.md
1. It should probably be explained in the documentation that fields marked with `flow(...)` should be excluded from wrapping in `makeObservable`/`makeAutoObservable`
2. Perhaps this place is a good place for example with `false` annotation `makeAutoObservable(this, { fetchProjects: false })`.
> Doc fix: observable fields is not specified

- .changeset/five-news-hammer.md
- packages/mobx/src/utils/iterable.ts
Really sorry, I might have introduced a bug [here](https://github.com/mobxjs/mobx/pull/3935)
thanks @zeldigas for reporting! 
For some projects setups, `Observablemap.prototype.forEach`, `ObservableSet.prototype.forEach` might throw an error on older browsers and Safari, I am genuinely sorry about this one.
I wrongfully assumed that `Iterator.prototype` is widely available but that's not the case.
> Fix(mobx): Safer method to consume Iterator.prototype

- docs/observable-state.md
-   [-] Added/updated unit tests
-   [-] Verified that there is no significant performance drop (`yarn mobx test:performance`)
Needs clarification.
> ECMA private fields with auto-accessor are in fact supported

- .changeset/set-interceptors.md
- packages/mobx/__tests__/v5/base/set.js
- packages/mobx/src/types/observableset.ts
I'm sorry for the missing related issue. 
Just figured out that the `newValue` returned from the `ObservableSet`'s interceptor is ignored. The following code still uses the base value passed to `add()` method. At a quick glance, the `set()` method of the `ObservableMap` just re-defines the value variable with the `change.newValue`. So I've reproduced the logic and added coupe of tests.
> Fix Set interceptors

- docs/react-integration.md
As suggested by @mweststrate : https://github.com/mobxjs/mobx/discussions/4537#discussioncomment-12689301
> Add reference to mobx-react-observer

- docs/installation.md
As suggested by @mweststrate : https://github.com/mobxjs/mobx/discussions/4537#discussioncomment-12689301
> Add observation plugins as option for React bindings

- packages/mobx/__tests__/decorators_20223/stage3-decorators.ts
- packages/mobx/src/types/computedannotation.ts
> inheritance should work with computed

- packages/mobx/src/types/observablevalue.ts
Make ObservableValue spy compatible with Symbol by converting it safely
> Fix "Cannot convert a Symbol value to a string"

- .changeset/fair-houses-rhyme.md
- packages/mobx/src/types/autoannotation.ts
> fix: Don't rewrap setters on the prototype

- package.json
- packages/mobx/__tests__/v5/base/typescript-tests.ts
- packages/mobx/src/api/observable.ts
- packages/mobx/src/types/observablemap.ts
- yarn.lock
This fixes https://github.com/mobxjs/mobx/issues/4573
The issue is that since TypeScript 5.9, a particular pattern for calling `observable.map` caused a compiler error. Comparing with the definition of `new Map`, I saw that we could fix this by using function overloads instead of the union type.
Before
After
> Fix issue with wrong inferred type of observable.map in TS 5.9+
