- mobservable.ts
I'm not too sure that this is correct, but I'm finding it necessary to add this change.
Hopefully you can tell me if it's the right change, or if I'm misusing the API.
> null-check currentValue

- getting-started.html
> Fix grammar mistake

- package.json
> run perf tests with tape

- package.json
- test/babel/babel-tests.js
Since babelifying is obsolete now ( https://github.com/tetsuo/mobservable/commit/09df8f492db5ba88fad53d1ba8cc2d33cda740e6#diff-ebf4480bad3515cc52fe84a53e34fc77R5)
> test babel indeed

- .travis.yml
- package.json
* Adds `test-travis` npm script specifically for travis
* Browser tests are also included
* Sends coverage output `after_success`
> Improve travis integration

- src/core.ts
> fix error msg typo

- index.js
- package.json
This will help systemjs bundler, which isn't totally intelligent about commonjs import implicit resolution, find the index.js.
> Minor tweak to the index imports

- docs/refguide/modifiers.md
fix a doubler function methode.
Add console log for client side code.
> Update modifiers.md according to description

- docs/refguide/observer-component.md
Btw: Thanks a LOT for this project!
> fix typo in function component example

- index.html
> Fix broken medium link in nav under https

- docs/intro/overview.md
Also bolded and italicized a key statement about the purpose of Mobx.
> Edited some text for readability

- docs/faq/faq.md
Just noticed some issues as I was reading the faq.
> Spelling fix in faq

- docs/README.md
- docs/faq/faq.md
When reading the good documentation, I was a bit distracted by some typos, remnants of edits, inconsistencies, etc.
I started to fix them.
Note I am not a native English speaker, and these changes are intuitive... So I can be wrong.
Note also: there is a "calling dispatcher or what more." which feels wrong, but I wasn't sure how to fix it...
I make this first PR, to know if you are OK with these changes, and accept I continue on the remainder of the doc, or if you prefer I stop here... :smile:
> Fix typos, improve consistency.

- src/api/observabledecorator.ts
The issue is described in fiddle: https://jsfiddle.net/Sl1v3r/ogkctduh/
> Fix @observable decorator (fixes #191)

- README.md
Add Smalldots MobX Store to related projects
> Smalldots MobX Store

- README.md
Currently, Decorators is in stage1 of the TC39 Process.
https://github.com/tc39/ecma262
I think it should call ES.Next.
Thanks.
> Decorators is not ES2015.

- docs/best/store.md
PR just fixes a typo. Related, though - would this benefit from a caveat along the lines of "unlike many Flux architectures, with MobX there is no need to normalize your data _for use in your store_"? I suppose it's obvious in context, but the existing wording could maybe be misinterpreted as meaning mobx has some bearing on, say, your database normalization.
> Clarifying normalization

- docs/refguide/observer-component.md
It seems this line has been copy-pasted with an extra unnecessary prop?
> Fix component render call

- README.md
> Added Google Play Music Desktop Remote to examples

- docs/SUMMARY.md
> Fix typo in docs.

- docs/intro/overview.md
> Fixed a typo.

- docs/refguide/action.md
- docs/refguide/create-transformer.md
- docs/refguide/modifiers.md
The PR fixes several typos across docs.
> Fix several typos in docs

- README.md
I added a link at the readme to another example using Mobx with a Flux pattern
> Add example React-Portal

- docs/refguide/autorun.md
- docs/refguide/observe.md
I really wish `intercept` and `observe` worked on nested observable structures but until then let's get the docs clear.
Related to #302
> Clarifications on what is observed and when

- src/api/autorun.ts
Implements optionally named autoruns suggested here:
https://github.com/mobxjs/mobx/issues/293
> Named autorun function

- README.md
Hey guys,
I made a starter kit, it would be nice if it could be linked here. :smile:
> add ts-mobx-react-starter-kit to README

- README.md
i add a new boilerplate to work reactjs and mobX
> add new boilerplate info in readme.md file

- README.md
sorry yesterday i write wrong url of my boilerplate . now i solve it and push again
> readme file my boilerplate  url error solve

- docs/best/react.md
Fixes various typos in react.md doc.
> Fixed typos in react.md

- docs/best/react.md
Github doesn't properly display table, This PR fixes that.
> fixed table format

- docs/best/pitfalls.md
Add a link to https://github.com/mobxjs/mobx/issues/219#issuecomment-220224813 where asMap is discussed and an example is present
> Add link to MobX roadmap issue for asMap

- src/types/modifiers.ts
> Make return type of `asMap` to `ObservableMap<any>`.

- docs/best/pitfalls.md
for more info: http://ell.stackexchange.com/questions/11305/it-is-or-it-are
> fix improper subject verb agreement

- docs/refguide/modifiers.md
Some example code became an error when running on browser.
> Fix code example on modifiers docs

- docs/README.md
"...chance to proof the philosophy..." => "...chance to prove the philosophy..."
> fix small typo

- docs/best/pitfalls.md
as discussed in this [issue](https://github.com/mobxjs/mobx/issues/476), added a short explanation on how to properly use mobx with react native list views, a code snippet was provided as well as a reference.
> docs: mobx with react native list views

- src/types/type-utils.ts
I ran into this error while doing some MobX code writing. I'm actually not sure Expecting is the correct word here. I assumed my best guess as a PR was better than an issue pointing to the typo.
> Expection -> Expecting

- docs/intro/overview.md
- :art: Cleanup.
- Grammar / awkwardness.
> :memo: Update overview.md

- docs/intro/concepts.md
> :memo: Updates concepts.md

- docs/refguide/api.md
This PR is the documentation companion for PR https://github.com/mobxjs/mobx/pull/608
If you are creating an extensive issue, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted ;-).
PR checklist:
> add documentation on isArrayLike

- README.md
Hello there!
I changed an example in readme to maintain consistency. Thanks for the reviewing.
> Change double quotes to single quotes in readme

- docs/refguide/action.md
- docs/refguide/computed-decorator.md
If you are creating an extensive issue, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted ;-).
PR checklist:
* [*] Updated (either in the description of this PR as markdown, or as seperate PR on the `gh-pages` branch. Please refer to this PR). For new functionality, at least [API.md](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md) should be updated
> added notes on setter actions.

- docs/refguide/observe.md
Docs polish regarding `intercept` & `disposer`.
> make "disposer" functionality more clear [ci skip]

- docs/faq/blogs.md
> Add link to my articles :-)

- docs/refguide/modifiers.md
> Fix some typos in modifiers.md

- docs/refguide/computed-decorator.md
As I become more familiar with MobX I hope that I can help clarify areas of the docs that are unclear.
If you are creating an extensive issue, you might want to open an issue with your idea first, so that you don't put a lot of effort in an PR that wouldn't be accepted ;-).
PR checklist:
> Small improvements to text

- src/types/observablearray.ts
- test/array.js
> removes deviation from ecmascript array, fixes #745

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- README.md
- src/api/observable.ts
- src/api/whyrun.ts
- src/core/atom.ts
- src/core/computedvalue.ts
- src/core/observable.ts
Hello! Mobx is great and I like it very much. I noticed a few apostrophes out of place and fixed them. If I were smarter I would fix bugs or write code but I will leave that to the smart people.
> Small, pedantic grammar fixes

- README.md
> Document "npm run small-build" before running "npm test" #GoodnessSquad

- docs/README.md
- docs/best/pitfalls.md
- docs/best/react.md
- docs/refguide/api.md
- docs/refguide/computed-decorator.md
- docs/refguide/create-transformer.md
- docs/refguide/extend-observable.md
- docs/refguide/modifiers.md
- docs/refguide/object.md
- docs/refguide/reaction.md
Some small grammar fixes in the gh-pages branch
> Proofreading the gh-pages docs

- docs/refguide/action.md
> missing backtick :rose:

- docs/README.md
npmcdn got renamed to unpkg a while ago
> Change npmcdn.com to unpkg.com

- docs/refguide/api.md
There is nothing React specific above the line but below. Correct me please if I am wrong.
> Fix sentence in api overview

- docs/best/pitfalls.md
I think this already got shipped as the corresponding PRs (#452, #489) got merged/closed 6 months ago.
> Update sentence in pitfalls.md

- docs/faq/examples.md
> Add link to a React Native + Mobx sample app

- getting-started.html
As per https://github.com/mobxjs/mobx/issues/634#issuecomment-273297901.
> Remove confusing Run button in Getting Started #GoodnessSquad

- docs/refguide/autorun.md
Thanks for such a great library and having amazing documentation to help grok it!
> Fixes type in `autorun` docs

- docs/refguide/api.md
PR checklist:
The above process doesnt apply to doc updates etc.
> Added missing period at the top of api.md

- CHANGELOG.md
- flow-typed/mobx.js
- src/types/observablearray.ts
> Fix observable array intercept typings

- CHANGELOG.md
- package.json
- scripts/single-file-build.js
- src/api/autorun.ts
- src/utils/utils.ts
> Expose ES2015 modules

- docs/refguide/computed-decorator.md
> fix spelling

- README.md
Hi. I've fixed README.md syntax. Thanks!
> Fix heading syntax in README.md

- docs/faq/examples.md
Link to a TypeScript + MobX example
> TypeScript + MobX example

- docs/faq/examples.md
Removed react-router from this project
> Changed mobx-ssr-example description

- src/core/derivation.ts
- test/autorun.js
> Fix: new observed derivations become stale

- docs/faq/blogs.md
> added codemy.net youtube playlist

- src/utils/utils.ts
> Make isArrayLike return type more accurate

- README.md
Hi, I had added the link of Chinese localization for MobX to the README. #897 
Please check the position of the  **Translations** link is appropriate? @mattruby
> add Chinese localization link to the README

- CODE_OF_CONDUCT.md
Updated Code of Conduct to correct spelling of `harrasment` to `harassment`.
> updated code of conduct - spelling of harassment

- docs/refguide/array.md
refs #934
And implementation is #936
> ObservableArray#findIndex (docs)

- docs/intro/overview.md
> change React.render to ReactDOM.render

- docs/faq/boilerplates.md
Link to a Create React App + MobX + React Router + Internationalization project with demo!
Thanks!
> Added 3RMXi to the Boilerplates 

- docs/faq/examples.md
Add two examples on codesandbox.io
> Code example projects on codesandbox.io

- faq/related.md
This library provides a simple integration of react-intl with mobx.
> Add mobx-react-intl

- docs/refguide/observe.md
> [DOC] "addedCount" instead "addCount".

- src/utils/decorators.ts
> Resolve typo

- src/mobx.ts
See #1043,  https://github.com/mobxjs/mobx-react-devtools/issues/64 ...
> Explicit default export

- CHANGELOG.md
- src/types/type-utils.ts
- test/typescript/typescript-tests.ts
fixes #1072, includes test as delivered through #1077, cc @farwayer
> Make sure fields are initialized before observing them, fixes #1072

- src/core/derivation.ts
Just some minor changes to the documentation so it is easier to read.
> Minor improvements to grammar and spelling in code docs

- .gitignore
- src/api/autorun.ts
- src/api/expr.ts
- src/api/extendobservable.ts
- src/api/isobservable.ts
- src/api/observable.ts
- src/api/tojs.ts
- src/api/whyrun.ts
- src/core/action.ts
- src/core/computedvalue.ts
- src/core/derivation.ts
- src/core/globalstate.ts
- src/core/observable.ts
- src/core/reaction.ts
- src/types/modifiers-old.ts
- src/types/observablearray.ts
- src/types/observableobject.ts
- src/types/observablevalue.ts
- src/types/type-utils.ts
Assorted minor fixes including:
* Alignment of jsdocs with code.
* Shortening of imports where possible.
* Ignoring Intellij IDEA project files.
> Minor jsdoc and imports fixes

- docs/refguide/computed-decorator.md
- docs/refguide/reaction.md
Documentation changes for #951
> Computed / Reaction comparer (docs)

- getting-started.html
> Improve wording in getting-started.html

- docs/refguide/array.md
> Fixed a typo

- docs/best/actions.md
> Fix example to use `this`

- docs/README.md
Thanks so much for MobX!
PR checklist:
> Some tiny wording suggestions

- docs/best/store.md
Better documentation concept.
PR checklist:
> Update name store StoreB to TodoStore

- src/core/computedvalue.ts
- src/core/derivation.ts
Some minor grammar improvements
> Minor grammar improvements

- .flowconfig
- src/api/action.ts
- test/babel/babel-tests.js
> @action get func(){} have accurate error messages #GoodnessSquadKyiv

- docs/best/pitfalls.md
> Fix typo in pitfalls.md

- docs/refguide/object.md
> [docs] Update function call in "Observable Objects"

- .gitignore
> Ignore IDEA's project files

- docs/refguide/map.md
Fixed a couple grammar mistakes
> Fix grammar

- docs/best/store.md
> grammar police

- docs/best/store.md
> Fix typo in docs/best/store.md

- CHANGELOG.md
- src/types/observablemap.ts
- src/utils/utils.ts
- test/map.js
Fixes https://github.com/mobxjs/mobx/issues/1243
> Map: Trigger reactions only on changed values

- docs/best/store.md
> typo and link asStructure docs

- docs/refguide/api.md
Remove a redundant parenthesis
> fix a mistake

- docs/refguide/action.md
> Fix syntax error

- flow-typed/mobx.js
Addresses issue #1282 
Like I said in the issue, I'm a Flow noob, so feel free to suggest other ways to do this.
> Fix flow typing errors

- package.json
- yarn.lock
I think we forgot to include this in https://github.com/mobxjs/mobx/pull/1103
> adds husky so that precommit runs when it should

- docs/refguide/boxed.md
> Remove extra . from boxed.md

- docs/best/actions.md
fixed a minor typo in the docs
> fixed typo in async actions docs

- docs/README.md
- docs/best/devtools.md
- docs/intro/overview.md
- docs/refguide/action.md
- docs/refguide/autorun.md
- docs/refguide/computed-decorator.md
- docs/refguide/observable-decorator.md
- docs/refguide/observable.md
- docs/refguide/observer-component.md
- docs/refguide/when.md
Hi,
according to this tweet from egghead i've changed the naming in the docs to lowercase: https://twitter.com/eggheadio/status/967130501658984448
greetings,
Tom
> egghead lowercase

- docs/refguide/api.md
- docs/refguide/autorun-async.md
> Add docs for autorunAsync scheduler function

- .gitignore
- docs/refguide/api.md
Handling the updates to the **API Overview** page.
> WIP: API Overview udpates

- flow-typed/mobx.js
> Fix flow typings

- src/api/action.ts
- src/api/actiondecorator.ts
- test/base/babel-tests.js
- test/base/typescript-tests.ts
> Make actions reconfigurable

- docs/refguide/object-api.md
Just a small change to fix a small typo!
> Fix documentation typo

- docs/refguide/observable-decorator.md
which i believe should point to modifiers
PR checklist:
> Fix link to  decorators.

- docs/refguide/api.md
> Expanded and updated docs on configure

- docs/refguide/expr.md
> Improve documentation of `expr`

- README.md
This is just small readme fix. Thx
> You are either optimal or not 

- docs/README.md
> Docs: fix the file link of flow typings

- src/api/decorate.ts
- src/api/observable.ts
- test/base/decorate.js
> Decorate: Fix in type-checked JS

- docs/best/pitfalls.md
React.render(...) => ReactDOM.render(...)
> Fix a typo

- README.md
Stumbled across this while learning about MobX.
No PR too small :)
> Tiny typo in Readme

- src/core/action.ts
this makes strict compilation error out
> add missing import of `fail`

- src/types/observablearray.ts
- test/base/strict-mode.js
fixed: https://github.com/mobxjs/mobx/issues/1568
> bugfix: allow changing while observable array initialization

- docs/refguide/object.md
assuming the method used to accept 4 args? :D
> typo 3th -> 3rd

- docs/refguide/expr.md
Now it matches https://github.com/mobxjs/mobx-utils
> Update docs `mobx.expr` to `mobxUtils.expr`

- CHANGELOG.md
I know it's a minor change, but I hope it's helpful!
> Fix small grammar error

- docs/README.md
I've read the paragraph several times and I am positive it should be `know` instead of `now`.
> fix grammatical error on Readme

- docs/best/decorators.md
On line 66, changed "that *both* all these" to "that all these".
> Fixed grammatical mistake

- CHANGELOG.md
Added an item to the CHANGELOG for version 3.0.0.
> Added an item to the CHANGELOG for version 3.0.0

- docs/refguide/reaction.md
> missing closing bracket ")"

- docs/refguide/extending.md
> Fix incorrect spelling.

- docs/intro/overview.md
> Fix Overview indentation

- docs/refguide/computed-decorator.md
> Update grammar in computed-decorator.md

- src/types/observableobject.ts
> Change property descriptor caches to null-prototype objects

- README.md
> Fixed typos, simplified sentences

- flow-typed/mobx.js
Added flow types for the comparer export.  
This closes #1668
> Add flow type for comparer export

- docs/best/actions.md
Changing in the website docs, Based on The [CHANGELOG.md](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#510--440)
> Update actions.md - Based on CHANGELOG docs

- docs/refguide/computed-decorator.md
> Fix typo in computed-decorator docs

- README.md
Hey,
There is a little doc update
> Display CDN urls as a sublist

- docs/refguide/modifiers.md
> Fix extendObservable example for modifiers

- src/types/observablearray.ts
- test/base/array.js
This PR fixes #[1839](https://github.com/mobxjs/mobx/issues/1839) for mobx@4
Will add changelog at another PR against master.
No need for docs, typings, performance.
> Fix array dehance (#1839) for mobx4

- src/api/action.ts
- src/api/actiondecorator.ts
- src/api/observable.ts
- src/core/reaction.ts
- src/utils/decorators.ts
> fix: type checking error under TypeScript 3.0 (fix #1837)

- docs/refguide/reaction.md
> Update typo in reaction.md

- README.md
I unified the quotation style of the source code in the Readme document.
PR checklist:
> Quotation marks style unification

- src/api/flow.ts
- src/types/observablemap.ts
PR checklist:
Run `yarn run quick-build` will fail because of some type errors. This PR fix them and quick-build works fine now 🤩
> fix: type error of TypeScript

- src/api/action.ts
- src/core/action.ts
- test/base/__snapshots__/spy.js.snap
- test/base/spy.js
> [action/createAction] - Keep observable reference.

- docs/refguide/observer-component.md
> Fix typo in Observer component docs

- README.md
> [README] - Beautify and update contributing section

- docs/refguide/computed-decorator.md
It might be a small change but it always feels nice to contribute :)
PR checklist:
> Fix: typo in computed docs

- scripts/build.js
Hi there. It fixes removing license header from minified version according this issue https://github.com/mobxjs/mobx/issues/1921
Details https://github.com/mishoo/UglifyJS2/issues/1985
> fix uglifyjs preamble (fixes #1921)

- docs/refguide/tojson.md
> document the recurseEverything option (again?)

- docs/README.md
I assume this was left here unintentionally @mweststrate
> Removed dangling link to www.faire.com

- CHANGELOG.md
https://github.com/mobxjs/mobx/pull/2011
> Adds computedConfigurable to changelog

- .github/stale.yaml
implementation for issue #2015
> Add stale bot config

- src/api/object-api.ts
> minor typings improvement

- docs/refguide/api.md
https://github.com/mobxjs/mobx/pull/2011
> Update docs for #2011

- docs/refguide/map.md
> #1979:  updated replace docs

- sponsors.md
> Fix typo in sponsors.md

- src/types/observablearray.ts
- test/base/array.js
> Add support to storing (non-observable) string / symbol based members on an array

- docs/book.json
- docs/styles/website.css
> Fix for H1 Covered by Codefund ads.

- flow-typed/mobx.js
This is the mobx4 PR for #2050
> [mobx4] Fix flow definition for Flow 103

- src/core/atom.ts
- src/types/observableobject.ts
I found two TS type checking errors.
> modify types

- src/utils/iterable.ts
- src/utils/utils.ts
fix https://github.com/mobxjs/mobx/issues/2070
relative https://github.com/mobxjs/mobx/pull/2071
> fix: self and global error in alipay appx

- src/api/become-observed.ts
- test/base/become-observed.js
> fix: onBecome(Un)Observed didn't trigger

- docs/refguide/observer-component.md
creatContext -> createContext
PR checklist:
> observer-component type fix

- src/mobx.ts
supplement of https://github.com/mobxjs/mobx/issues/2070
> Use convergent global

- src/internal.ts
> chore: fix minor typo

- src/core/action.ts
- src/core/globalstate.ts
- src/mobx.ts
- test/base/action.js
- test/base/api.js
Backport of https://github.com/mobxjs/mobx/pull/2117 for mobx4
> expose startAction and endAction [mobx4]

- flow-typed/mobx.js
- src/api/autorun.ts
- src/api/configure.ts
- src/api/when.ts
- src/core/action.ts
- src/core/derivation.ts
- src/core/globalstate.ts
- src/core/observable.ts
- src/core/reaction.ts
- test/base/autorun.js
- test/base/autorunAsync.js
- test/base/reaction.js
- test/base/strict-mode.js
> feat: derivationRequiresObservable & observablesRequiresReaction (mobx4)

- src/utils/comparer.ts
- src/utils/eq.ts
- test/base/extras.js
> Shallow comparer [mobx4]

- src/api/flow.ts
> fix error message typo

- src/utils/utils.ts
See #2184 
The `mockGlobal` issue is already fixed in this branch apparently so no need to cherry pick second commit
PR checklist:
> allow mobx to run in web worker (against mobx4-master)

- flow-typed/mobx.js
- src/api/flow.ts
- src/mobx.ts
- test/base/api.js
- test/base/flow.js
> cancelled flow() to reject with new FlowCancellationError - mobx 4

- CHANGELOG.md
Just fixing some mistakes in the changelog
> Fix changelog mistake

- CHANGELOG.md
- src/core/derivation.ts
- test/base/strict-mode.js
fix #2195, add test
PR checklist:
<s>* [ ] Updated `/docs`. For new functionality, at least `API.md` should be updated</s>
<s>* [ ] Added typescript typings</s>
> fix #2195, add test

- CHANGELOG.md.orig
- src/core/derivation.ts
> fix: missing allowStateReadsEnd on exception branch (mobx4)

- src/utils/utils.ts
Just a tiny issue with the indefinite acricle.
> Fix the indefinite article issue.

- docs/best/react.md
> docs: typo fixed

- package.json
- src/api/action.ts
- test/base/typescript-tests.ts
- yarn.lock
Fixed type inference of the action callback arguments. Added type tests for the action callback arguments.
> Backport of #2217 and #2213 for Mobx 4

- docs/faq/faq.md
The FAQ and the README contradict each other re: browser support, and the README seems correct. I wasn't sure how much to duplicate the info here. Feel free to rewrite this, but I thought the FAQ should be updated. Thanks!
> Update browser support

- CHANGELOG.md
- src/mobx.ts
- test/base/api.js
Motivation:
https://github.com/mobxjs/mobx-react/issues/806
> Expose allow state reads start end

- README.md
I just started Spectrum community. Not sure if it will be used, but I feel it's better for anything worth keeping around. If you have some other ideas were to spread the existence of it, let me know.
https://spectrum.chat/mobx
> Add Spectrum badge to readme

- docs/assets/getting-started-assets/javascripts/codemirror/lib/codemirror.css
- docs/assets/getting-started-assets/javascripts/codemirror/lib/codemirror.js
I’m not sure how correct this decision is. 😅
But I noticed issue #2282  and decided to help return the lost packages.
So both files are taken from https://github.com/codemirror/CodeMirror
> Fix Getting Started #2282: add missing codemirror files

- docs/best/decorators.md
> Fix typo in best/decorators.md

- .gitpod.yml
- CONTRIBUTING.md
- README.md
Hi! :slightly_smiling_face: 
As discussed in #2316 This Pr simplifies code contributions and reviews by fully automating the dev setup with Gitpod (a free online VS Code like IDE). 
With a single click, it'll launch a ready to code workspace with everything setup.
You can give it a try on my fork of the repo via this link:
https://gitpod.io/#https://github.com/nisarhassan12/mobx
this is how it looks:
Also for having these review comments in PRs and [pre-built](https://www.gitpod.io/docs/prebuilds/) workspaces, the Gitpod App has to be installed https://github.com/apps/gitpod-io I have added the configuration required you just have to install the app.
The app can only be installed by individual developers on their own account (i.e. there is no org billing or so). It can then be …
> simplify code contributions + reviews by fully automating the dev setup.

- src/v4/types/observableobject.ts
- src/v5/types/observableobject.ts
Resolves #2330 
-   [x] Updated typings
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2332"><img src="https://gitpod.io/api/apps/github/pbs/github.com/inoyakaigor/mobx.git/5d59b7afaf30cc9fae6fea6ad4cebb3c7f6c9e0b.svg" /></a>
> Change types for IObjectWillChange and IObjectDidChange to generic

- docs/refguide/action.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2333"><img src="https://gitpod.io/api/apps/github/pbs/github.com/xchmelmilos/mobx.git/c188104e0fc83e0594173d9fc296c7d4712d2e3d.svg" /></a>
> added links to docs, fixed link to enforceActions

- docs/refguide/inject.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2345"><img src="https://gitpod.io/api/apps/github/pbs/github.com/haleyhitch/mobx.git/4360bf76fc444694600f3f1b514206055b64a248.svg" /></a>
> Added link for `React.createContext` to docs

- src/v4/core/observable.ts
- src/v5/api/extendobservable.ts
- src/v5/core/observable.ts
- test/v5/base/observables.js
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2351"><img src="https://gitpod.io/api/apps/github/pbs/github.com/zhenyong/mobx.git/1b049b14de9602719ad59173b336778bbed9ee9d.svg" /></a>
> Fix spelling error

- README.md
- docs/README.md
I have been learning MobX and using it for projects at work for about a year now. I struggled with this section of the documentation when I first came across it.  Specifically, I did not understand which aspect of spreadsheet cells using `observable` was like. My enhancement adds some context to the metaphor so that it is clear *how* `observable` is like a spreadsheet cell.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2359"><img src="https://gitpod.io/api/apps/github/pbs/github.com/jgarboza813/mobx.git/d23b3589c46ecbb5e883744144dd1b07f9896235.svg" /></a>
> Enhancement to observable documentation

- docs/refguide/computed-decorator.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2362"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rdworth/mobx.git/1504cc9632640e79ce4ee931455cb9f4d681c7e4.svg" /></a>
> Typo managment -> management

- website/static/css/custom.css
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2367"><img src="https://gitpod.io/api/apps/github/pbs/github.com/mobxjs/mobx.git/3a6cb594cde8212a5f1dbccb0b09a4753202e7b7.svg" /></a>
> docs: Added black lives matter banner

- docs/refguide/map.md
Hi guys,
Thank you so much for the work you are doing on this library!
Hope you don't find this PR too tiny. I just read the docs, found the tiny error and thought why not.
Have a good day!
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2366"><img src="https://gitpod.io/api/apps/github/pbs/github.com/akd-io/mobx.git/d3d8c763e421d5d9a909eda346a8262827502a42.svg" /></a>
> Tiny syntactic fix in Map docs

- src/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
It's done btw, tests are expected to fail
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2373"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/fec22b0b3878afc7992b675cae7d8f08d2671e2a.svg" /></a>
> fix #2326 for v6

- test/v5/base/map.js
The `debugger` statement would take effect in Visual Studio Code's Javascript Debug Terminal. But I don't expect to debug here.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2414"><img src="https://gitpod.io/api/apps/github/pbs/github.com/MoonBall/mobx.git/5280827b37f21d808f30727060f12e96c98c00a1.svg" /></a>
> remove `debugger;`

- website/static/css/custom.css
The first image below show the case that BLM covers the input search.
The second image below show the result of the fix.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2421"><img src="https://gitpod.io/api/apps/github/pbs/github.com/MoonBall/mobx.git/ab0673407050f133f41232f22a5f36b4be14c3fd.svg" /></a>
> fix: BLM covers the search input in mobile

- website/static/css/custom.css
fix https://github.com/mobxjs/mobx/issues/2413.
The following image shows the result after the fix.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2420"><img src="https://gitpod.io/api/apps/github/pbs/github.com/MoonBall/mobx.git/da27c1fe4015916a548419bf837990cc34ce18e1.svg" /></a>
> fix: log doesn't align with other section of the footer(#2413)

- src/v4/api/extendobservable.ts
- src/v5/api/extendobservable.ts
- src/v5/core/globalstate.ts
- src/v5/utils/utils.ts
- test/v4/base/observables.js
- test/v5/base/observables.js
Fix https://github.com/mobxjs/mobx/issues/2386 on v5.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2412"><img src="https://gitpod.io/api/apps/github/pbs/github.com/MoonBall/mobx.git/2ad012c3280f334d3cb0d9c906722eb8194d1f2a.svg" /></a>
> extendObservable can be used late and support non-enumerable getters.

- CHANGELOG.md
- src/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
port of #2426 for mobx6
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2431"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/ef777535db076f208deb7fd7760f4db445d37b14.svg" /></a>
> fix array dehancing v6

- CHANGELOG.md
- src/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
Fixes #2432
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2433"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/241b091161923ed879c45a47cd3c845cd15da4f4.svg" /></a>
> fix array.reduce without initial value #2432 v6

- CHANGELOG.md
- src/v4/types/observablearray.ts
- src/v5/types/observablearray.ts
- test/v4/base/array.js
- test/v5/base/array.js
Fixes #2432
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2434"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urugator/mobx.git/2297419b74b89cffd89fdd4626c7fde916692ac1.svg" /></a>
> fix array.reduce without initial value #2432 v4v5

- README.md
Just a small update to Readme :)
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2435"><img src="https://gitpod.io/api/apps/github/pbs/github.com/chase-manning/mobx.git/c9625f9c7100373f63ee236bc91b88f28f137832.svg" /></a>
> Fixed Formatting Issue with Sponsor Monthly Amount

- docs/README.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2441"><img src="https://gitpod.io/api/apps/github/pbs/github.com/CodingCarter/mobx.git/40ce8807b4cecb9b807453be0af73e27237e283e.svg" /></a>
> grammar: fix dollar sign position

- src/api/observable.ts
Closes #2438
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2440"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Amareis/mobx.git/405d924f464b7cea54080f5dd38838f51a108dfd.svg" /></a>
> FIxed typings (function properties instead of methods in decorators) mobx6

- src/api/decorators.ts
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2454"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Rain120/mobx.git/03b60dde8a8b72399ef82e3343170e000466d3b1.svg" /></a>
> fix: decorator symbol key

- CHANGELOG.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2466"><img src="https://gitpod.io/api/apps/github/pbs/github.com/vkrol/mobx.git/ca755422707f328ba9a002a26f94149c3b53cac4.svg" /></a>
> Fix typo in CHANGELOG.md (observableMap -> observableSet)

- packages/mobx-undecorate/README.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2469"><img src="https://gitpod.io/api/apps/github/pbs/github.com/vkrol/mobx.git/6aead41714030015dc1bf831a0b6f2f9699f0564.svg" /></a>
> Add missing backtick in mobx-undecorate/README.md

- src/api/makeObservable.ts
fix: #2480
It's my first commit. if i made a mistake. tell me plaese. 
Thank you.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2481"><img src="https://gitpod.io/api/apps/github/pbs/github.com/dpudpu/mobx.git/a9b4dad42617321dfe767a6867e46200d37a3624.svg" /></a>
> Rename parameters in makeAutoObservable

- packages/mobx-undecorate/cli.js
No tests or any other changes affected ( I think).
Cannot verify this works ok cross-platform though.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2472"><img src="https://gitpod.io/api/apps/github/pbs/github.com/janpieterz/mobx.git/22b9a731dc92b76075a98437c323ca23ae94eb42.svg" /></a>
> Add shell and change directory path of mobx-undecorate

- docs/actions.md
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2488"><img src="https://gitpod.io/api/apps/github/pbs/github.com/iswara108/mobx.git/14c786dbf8f83fdb68d3d0030bf512b33beffc88.svg" /></a>
> add "async" declaration

- website/siteConfig.js
Related to #2497 
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2518"><img src="https://gitpod.io/api/apps/github/pbs/github.com/leader22/mobx.git/090f683959a7fa339957acfa972ca2723ab3b97b.svg" /></a>
> Docs: Make EDIT button works

- docs/react-integration.md
Updated computed props part of React integration docs. It should address issue https://github.com/mobxjs/mobx/issues/2487
- Cleaned up the example a bit by updating imports
- Removed mention and usage of deprecated [`useAsObservableSource`](https://github.com/mobxjs/mobx-react-lite/tree/master#useasobservablesourcetsource-t-t-deprecated) hook
- Updated demo timer to make it a working example. Not really a MobX issue, but it's ok to have actual working examples in docs
---
As a sidenote, I noticed that some examples might have unused imports in them or even a slight mistake like the one with the timer example function `increaseTimer` not actually being called so it makes the example not really a working one.
I might try to catch some time to go through more example in the next few days, …
> Docs: update React integration computed props tip

- docs/computeds-with-args.md
I think derivations should be pure? 
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2514"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nilshartmann/mobx.git/31b74ed4a9893f211e0b720c6ccccff36c627a80.svg" /></a>
> Docs: Derivations should be pure

- docs/observable-state.md
Fixes #2497 
Update TypeScript 🗒️ for `makeObservable` docs.
<a href="https://gitpod.io/#https://github.com/mobxjs/mobx/pull/2517"><img src="https://gitpod.io/api/apps/github/pbs/github.com/leader22/mobx.git/6987ca6114cb20375ea3b9035aedcd85db2950b5.svg" /></a>
> Docs: Update observable-state.md

- .github/PULL_REQUEST_TEMPLATE.md
Mobx 6 is already merged to master! 🎉 
See also https://github.com/mobxjs/mobx/pull/2544#issuecomment-713609587
> Remove mobx6 disclaimer from PR Template

- .changeset/many-cars-do.md
- packages/mobx-undecorate/README.md
- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/src/undecorate.ts
> Fix #2558 Undecorate removes non-mobx decorators

- packages/mobx-undecorate/src/undecorate.ts
I know this is a totally unimportant change but I noticed it while looking at the code :)
> Fix typo in undecorate.ts

- packages/mobx-undecorate/README.md
- packages/mobx-undecorate/__tests__/undecorate.spec.ts
- packages/mobx-undecorate/src/undecorate.ts
> Fix #2540 makeObservable not added to imports

- .changeset/config.json
- .changeset/strange-coins-sin.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/types/observableobject.ts
Fixes #2614 
Also updated changeset config (baseBranch: mobx6 => main)
> Fix #2614 - makeObservable does not respect options.name

- docs/README.md
Hey guys as I was going through the documentation for version 5 I noticed some broken links so I fixed them in this PR 😄
> Update broken links on mobx4and5 docs

- .changeset/calm-camels-learn.md
- packages/mobx/src/errors.ts
A small fix for minified mobx error reference ;)
> Fix broken error reference in errors.ts

- docs/actions.md
- docs/react-optimizations.md
There are mismatched parentheses in `actions.md`, `react-optimizations.md`
> Fix typo in actions.md, react-optimizations.md

- docs/computeds-with-args.md
Hello
I found a spelling error while reading the document and tweaked some of the grammar to make the reading flow more smoothly.
> docs: grammar correction

- docs/actions.md
- docs/configuration.md
- docs/observable-state.md
- docs/subclassing.md
- website/sidebars.json
Mostly regarding actions and subclassing
> Doc improvements

- website/siteConfig.js
Seeking more ranslation volunteers, when we finish the translation work, we can edit the config like this:
```diff
- { href: "https://zh.mobx.js.org", label: "中文(寻求翻译)" },
+ { href: "https://zh.mobx.js.org", label: "中文" },
```
`寻求翻译` = `seeking translation`
> https://zh.mobx.js.org/README.html
> docs: seeking more translation volunteers

- docs/react-integration.md
<!--
Thanks for taking the effort to create a PR! 🙌
👋 Are you making a change to documentation only? Yest
> fix link to mobx-react-lite

- docs/observable-state.md
> Fix missing import

- packages/mobx/CHANGELOG.md
Some links were broken. so fixed it
> Fix broken links

- .changeset/calm-wolves-cover.md
- packages/mobx/__tests__/v4/base/tojs.js
- packages/mobx/__tests__/v5/base/tojs.js
- packages/mobx/src/api/tojs.ts
> Fix #2903: toJS works with computed value props

- .changeset/purple-pianos-obey.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/types/autoannotation.ts
> Fix #2948: flow ignores autoBind option

- README.md
- docs/README.md
Credit to @maghrout for his eagle eye 😅
> Failed attempt to fix world's most insignificant typo

- docs/react-integration.md
This example refers to the ``useState with observable class`` block where ``myTimer`` is not defined. A ``timer`` is defined instead. Full example:
```javascript
const TimerView = observer(() => {
const [timer] = useState(() => new Timer())
useEffect(() => {
const handle = setInterval(() => {
timer.increaseTimer()
}, 1000)
return () => {
clearInterval(handle)
}
}, [timer])
return <span>Seconds passed: {timer.secondsPassed}</span>
})
```
> docs: fix timer example

- .changeset/fluffy-pumas-impress.md
- packages/mobx/src/api/observable.ts
> chore: observable use internal constants

- .changeset/spotty-cheetahs-invite.md
- packages/mobx/src/utils/comparer.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#polyfill
> Polyfill `Object.is` for old/unsupported browsers

- website/i18n/en.json
- website/siteConfig.js
> doc: add korean documentation header link

- .changeset/loud-rules-count.md
- packages/mobx/src/core/computedvalue.ts
> Correction for #2998, missing __DEV__ check, changeset typo

- docs/defining-data-stores.md
The code in the example uses the mobx reaction function yet the reaction function isn't included in the imports.  I've added it.
> Include reaction in imports

- packages/mobx/src/types/observablemap.ts
> refactor(mobx): remove the function updateHasMapEntry_

- packages/mobx/src/api/iscomputed.ts
> refactor(mobx): update function to return early

- packages/mobx/src/core/globalstate.ts
> refactor(mobx): added comment explaining why setTimeout is needed

- packages/mobx/src/core/observable.ts
> refactor(mobx): replace hack for repeating string with .repeat

- packages/mobx/src/types/observablearray.ts
> fix(mobx): assert that array length in obs array is not NaN

- docs/enabling-decorators.md
> doc: fix typo in enabling-decorators.md

- .changeset/friendly-moons-drum.md
- packages/mobx-react-lite/__tests__/observer.test.tsx
- packages/mobx-react-lite/src/observer.ts
https://github.com/mobxjs/mobx/discussions/3167
> mobx-react-lite: Support legacy contextTypes

- .github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/mobxjs/mobx/issues/3181
> Fix outdated PR template (Close #3181)

- docs/installation.md
in reaction to:
https://github.com/mobxjs/mobx/issues/3187#issuecomment-971659488
> doc: env info

- docs/api.md
Update `toJS` docs, in line with the changes in [this PR](https://github.com/mobxjs/mobx/pull/3239)
> Update `toJS` docs

- .changeset/tall-meals-walk.md
- packages/eslint-plugin-mobx/preview/no-anonymous-observer.js
- packages/eslint-plugin-mobx/src/no-anonymous-observer.js
> fix `no-anonymous-observer` autofix for arrow functions without BlockStatement body

- .changeset/silly-lions-run.md
- packages/mobx/__tests__/v5/base/map.js
- packages/mobx/src/types/observablemap.ts
https://github.com/mobxjs/mobx/discussions/3255
> fix: observable map initialization violates `enforceActions: "always"`

- .changeset/fuzzy-coins-beam.md
- packages/mobx/__tests__/v5/base/make-observable.ts
- packages/mobx/src/types/flowannotation.ts
> Fix #3271 flow.bound

- website/static/getting-started.html
Fix wording in one sentence in getting-started.html
> Fix wording in one sentence in getting-started.html

- docs/assets/getting-started-assets/javascripts/JSXTransformer.js
- docs/configuration.md
> chore: Correct typos

- docs/computeds-with-args.md
Fix typo where missing close parenthesis.
> docs: fix typo

- CONTRIBUTING.md
> Adding hints how to get the code running

- .changeset/silly-planets-remember.md
- packages/mobx/src/api/observable.ts
See https://github.com/microsoft/TypeScript/issues/49489
> Apply 'object' constraint where required

- packages/mobx-react/README.md
fix Bundlephobia link for mobx-react
> docs: fix Bundlephobia link  for mobx-react

- website/siteConfig.js
Belated, as it kept lingering on my to-do list, but added a Ukrainian flag as a tiny token of respect to their fight against the Russian invasion.
> docs: Add Ukraine flag

- scripts/build.js
> chore: remove the unused variables

- docs/actions.md
I was confused by the return type of the unboxed Promise returned by `flowResult`. It seems the documentation is incomplete since the generator is not returning anything.
https://codesandbox.io/s/vigorous-paper-zp79z5?file=/src/reduced.ts
https://codesandbox.io/s/vigorous-paper-zp79z5?file=/src/store.ts
> doc: fix flowResult example

- .changeset/bright-pianos-divide.md
- packages/mobx/__tests__/v5/base/become-observed.ts
- packages/mobx/src/types/observableset.ts
- packages/mobx/src/types/type-utils.ts
> Fix #3595 onBecomeObserved is not called for ObservableSet

- docs/observable-state.md
Though this should be clearly understood from the rest of the doc (it wasn't clear for me :sweat: ), I believe it should be stated explicitly.
> update makeObservable doc

- packages/mobx-undecorate/src/undecorate.ts
The problem was caught here: https://github.com/microsoft/TypeScript/pull/52947#issuecomment-1443147890
> chore: properly use primitive types over wrappers

- .changeset/grumpy-seals-impress.md
- packages/mobx-react-lite/src/utils/UniversalFinalizationRegistry.ts
> Fix #3643 FinalizationRegistry support check

- .changeset/old-candles-wonder.md
- packages/mobx-react-lite/package.json
Without this, the package won't be included downstream.
Fixes #3666
> fix(mobx-react-lite): Add missing dependency

- docs/enabling-decorators.md
> Fix example in enabling-decorators.md

- packages/mobx-react-lite/src/useObserver.ts
- packages/mobx/src/core/atom.ts
These are just some small changes that I discovered while studying the internal implementation of mobx.
> Fix: add missing returning type and fix typo

- .changeset/polite-laws-provide.md
- packages/mobx-react/__tests__/observer.test.tsx
- packages/mobx-react/src/observerClass.ts
> fix #3730: class component does not react to state changes performed before mount

- packages/mobx-react/__tests__/timerBasedFinalizationRegistry.tsx
- packages/mobx-react/__tests__/utils/killFinalizationRegistry.ts
> add test for #3776

- docs/observable-state.md
> Fixed typo in observable-state.md

- packages/mobx-react-lite/tsconfig.json
-   [] Added/updated unit tests
-   [] Updated `/docs`. For new functionality, at least `API.md` should be updated
-   [] Verified that there is no significant performance drop (`yarn mobx test:performance`)
* Fix building of Mobx react lite
> Fix for #3898

- docs/installation.md
> doc: update broken link

- .changeset/wet-months-explain.md
- packages/mobx/__tests__/v5/base/set.js
- packages/mobx/src/types/observableset.ts
- packages/mobx/src/utils/utils.ts
> fix 3919: new set methods not working with observable set

- package.json
- yarn.lock
#3923 , root cause https://github.com/testing-library/react-testing-library/releases/tag/v15.0.6
> fix:  act warning

- tsconfig.json
> chore: fix release / build issue

- docs/enabling-decorators.md
> Vite es-decorators configuration example

- docs/enabling-decorators.md
In relation to issue #4248 , adding a note to decorator doc, explain the risk of new decorator before we find a solution
> Adding note regarding accessor

- .changeset/tiny-rice-walk.md
- docs/reactions.md
- packages/mobx/__tests__/v5/base/reaction.js
- packages/mobx/src/core/reaction.ts
Discussion: https://github.com/mobxjs/mobx/discussions/4559
> feat: Explicit Resource Management support in reactions

- .changeset/slow-carpets-breathe.md
- .changeset/twelve-bees-turn.md
> chore: forgotten changesets
